refactor: Turn JSON-serialization into the `Bones`
viur-framework/viur-core pull request #1000
Opened 2023-12-18 16:45 UTC by ArneGudermann

This PR moves the JSON rendering to the bones.
Resolves #978.

2023-12-19 08:13 UTC, phorward submitted a review, later dismissed
Hello @ArneGudermann,
thanks for facing this! 
I'm a little bit unlucky with the naming regarding values and single_values... but this is a general problem in the current implementation that must be redesigned in the whole bone system.

For now, we can make it this way. ~Can you please add the suggestion to the VIUR4 issue #647, this is important to clean-up the interface, especially for newbies.~ Oops, this was related to the structure rendering, I'm sorry.

2023-12-19 08:15 UTC, phorward commented on src/viur/core/bones/relational.py
> +                "dest": value["dest"].render_bone_values(),
Oops, this was related to the structure rendering, I'm sorry.

2023-12-20 19:40 UTC, sveneberth requested changes
Sorry, but this PR in this form makes no sense to me. The rendering of respectively for ALL renderers should be in the bones, not just for one. In addition, `render_single_value` should be passed the current renderer by argument, so that different outputs can be generated.

2023-12-20 22:03 UTC, phorward commented
> The rendering of respectively for ALL renderers should be in the bones, not just for one. In addition, `render_single_value` should be passed the current renderer by argument, so that different outputs can be generated.

The intention of this PR is to turn a JSON-serializable rendering of values into the bones logic, for easier maintenance. It will be the base for further developments regarding JSON, XML and MsgPack renderers, because rendering stuff into JSON-serializable structures is heavily used in several situations.

The only special case is the HTML renderer for Jinja, which mostly just provides an adaption of the existing objects for faster access. This is a pull request on its own.

Indeed, this pull request doesn't address all cases of the concept, but this wasn't the goal.

2023-12-20 22:10 UTC, phorward commented on src/viur/core/render/json/default.py
> +            skel_list = kwargs["skellist"]
@ArneGudermann can you please name it back into `skellist`?

2023-12-21 10:55 UTC, phorward approved these changes

2024-01-12 16:54 UTC, phorward commented
@ArneGudermann please fix the conflicts with current develop.
@sveneberth would you like to discuss this in viur-meeting, or do you comply?

2024-07-11 21:00 UTC, phorward commented
@ArneGudermann I would like to add this PR to viur-core 3.7, can you please resolve the conflicts and we can make another iteration over it?

2025-07-07 22:12 UTC, phorward commented on src/viur/core/bones/record.py
> +            "using": self.using().structure()
Keep the `,`!

```suggestion
            "using": self.using().structure(),
```

2025-07-07 22:18 UTC, phorward commented on src/viur/core/bones/base.py
> +    def render_value(self, skel: "SkeletonInstance", bone_name: str):
Rename the function to something like just `value`. Avoid using the word "render", as it directly refers to renders.

```suggestion
    def value(self, skel: "SkeletonInstance", bone_name: str) -> t.Any:
```
Docstring is also missing entirely!

2025-07-07 22:21 UTC, phorward commented on src/viur/core/bones/base.py
> +    def render_single_value(self, value):
The "single"-values API is absolutely confusing. Please use an entirely different name, and make it somewhat private.

Proposal:
```suggestion
    def _atomic(self, value):
```

A docstring is also missing here.

2025-07-07 22:22 UTC, phorward commented on src/viur/core/render/json/default.py
> +            vals = [_skel.render_bone_values() for _skel in skel]
This entire code path is stupid and a relict.
It should be removed.
```suggestion
            raise ValueError("renderEntry cannot handle lists")
```

2025-07-07 22:22 UTC, phorward commented on src/viur/core/render/json/default.py
> +            vals = skel.render_bone_values()
```suggestion
            vals = skel.values()
```

2025-07-07 22:23 UTC, phorward commented on src/viur/core/skeleton/instance.py
> +
```suggestion
    def values(self):
        return {
            bone_name: bone.value(self, bone_name) for bone_name, bone in self.items()
        }

```

Docstring is missing!

2025-07-07 22:24 UTC, phorward commented on src/viur/core/render/json/default.py
> +            skellist = [skel.render_bone_values() for skel in skellist]
```suggestion
            skellist = [item.values() for item in skellist]
```

2025-07-08 08:57 UTC, ArneGudermann commented on src/viur/core/skeleton/instance.py
> +
Now we have the `values` methode here and here https://github.com/viur-framework/viur-core/blob/c1e9d700c2cc4d7f78e3a39b2dc6afb546802c2e/src/viur/core/skeleton/instance.py#L115

2025-07-08 12:35 UTC, ArneGudermann commented on src/viur/core/skeleton/instance.py
> +
@phorward

2025-07-08 20:23 UTC, phorward commented on src/viur/core/skeleton/instance.py
> +
You're right... I didn't recognize this.

What do you think of using the wording *simplified* for this case, rather than *get_values*? `skel.simplified()` is like `skel.values()`, but returns the plain, simplified version of the values, which can be simply serialized to JSON, BSON, XML... ?

2025-07-14 18:01 UTC, phorward requested changes
Minor fixes of code around.
We can merge afterwards!

2025-07-14 18:01 UTC, phorward commented on src/viur/core/render/json/default.py
>                         "invalidatedFields": x.invalidatedFields} for x in skel.errors]
```suggestion
            errors = [
                {
                    # FIXME: Better names in ViUR4
                    "severity": error.severity.value,
                    "fieldPath": error.fieldPath,
                    "errorMessage": error.errorMessage,
                    "invalidatedFields": error.invalidatedFields
                } for error in skel.errors
            ]
```

2025-07-14 20:34 UTC, phorward approved these changes

2025-07-14 20:37 UTC, merged