refactor: Tasks module
viur-framework/viur-core pull request #1016
Opened 2024-01-08 14:29 UTC by phorward

Refactoring the tasks module.

- Restructured `imports`
- Renamed preprocessJsonObject into _preprocess_json_object
- Renamed jsonDecodeObjectHook into _decode_object_hook
- Concise use of datetime-ISO-format
  - (addresses issue #486 as well!)
  - breaking change between viur-core 3.5 and viur-core 3.6 when applied to a project where tasks are still open

2024-01-26 10:44 UTC, sveneberth requested changes

2024-01-26 10:44 UTC, sveneberth commented on src/viur/core/tasks.py
> +        transport=tasks_v2.services.cloud_tasks.transports(channel=grpc.insecure_channel(os.getenv("TASKS_EMULATOR")))
```suggestion
        transport=tasks_v2.services.cloud_tasks.transports.CloudTasksGrpcTransport(channel=grpc.insecure_channel(os.getenv("TASKS_EMULATOR")))
```

2024-01-26 10:47 UTC, phorward commented on src/viur/core/tasks.py
> +        transport=tasks_v2.services.cloud_tasks.transports(channel=grpc.insecure_channel(os.getenv("TASKS_EMULATOR")))
Hoppela!

2024-01-26 11:12 UTC, sveneberth requested changes

2024-01-26 11:12 UTC, sveneberth commented on src/viur/core/tasks.py
> +    elif isinstance(obj, datetime):
```suggestion
    elif isinstance(obj, datetime.datetime):
```

2024-01-26 11:40 UTC, sveneberth approved these changes
With the fix https://github.com/viur-framework/viur-core/pull/1043 this seems to work

But please make the linter happy too :smile:

2024-02-12 16:02 UTC, sveneberth approved these changes

2024-02-12 16:14 UTC, merged