fix: `RelSkel.fromClient()` and `BaseSkeleton.fromClient()` with empty/unset data
viur-framework/viur-core pull request #1023
Opened 2024-01-12 12:35 UTC by phorward

Some necessary improvements to `RelSkel.fromClient()` and `BaseSkeleton.fromClient()` for integration with the new vi-admin.

- RelSkel.fromClient() is valid when no data is provided and all fields are not required
- errors are now being iterated only once
- better "incomplete" detection
- comments (huh, woooow!)
- removed `allowEmptyRequired`-parameter from all functions as it is not necessary anymore
- tested against normal bones, RelationalBones with using skel, and RecordBones with several bone configurations

2024-01-12 16:21 UTC, phorward commented
Hello, there are some edge cases where the validation might not be as expected, e.g. when there is a `RecordBone(multiple=False)`, which is not required, but has a required field. In this case, the RecordBone will be flagged invalid when any value for the RecordBone was provided, but not a required one.

By the current design, this behavior is correct: The RecordBone itself is not required, therefore its content is not required. When its content is provided, but invalid, is is correctly rejected.

I'm sure this won't break the whole system now, as several tests worked correctly and as expected. The handling is now better, as vi-admin does not send fields which aren't there.

I would like to bring this into viur-core 3.5.11 asap, as it is required for a project.

2024-01-12 18:35 UTC, phorward commented
The latest commit entirely removes `RelSkel.fromClient()` as it becomes equal to `BaseSkel.fromClient()`, and the custom stuff is done in subclassed `Skeleton.fromClient()`. Tests worked.

2024-01-15 13:36 UTC, sveneberth requested changes
I tested this with `RelationBones` and couldn't find any error which is caused by this change.

2024-01-15 15:48 UTC, phorward commented on src/viur/core/skeleton.py
> +            or (str(data.get("nomissing")) == "1")
Yes, thanks. Indeed, IMHO such special parameters should use a (configurable) "viur-"-prefix or similar, or "nomissing" must be reserved name.

2024-01-16 12:29 UTC, sveneberth approved these changes

2024-01-17 10:51 UTC, ArneGudermann approved these changes

2024-01-17 11:21 UTC, merged