refactor: Modularization of `File`
viur-framework/viur-core pull request #1046
Opened 2024-01-26 15:30 UTC by phorward

This partly refactors the `File`-module to the following:

- Moved and renamed `utils`-functions into `modules.file` as they belong there
- Removed unused variables and unused functions
- Fixed calls to prior `utils`-functions (e.g. from the renders)
- Fixed `expired`-flag in srcSetFor() as this was inconsistent to `downloadUrlFor`

2024-01-29 10:35 UTC, ArneGudermann requested changes
Thank you @phorward  for the PR. I have one more question. Shouldn't we include the functions that are now out of the utils in the [__UTILS_NAME_REPLACEMENT](https://github.com/viur-framework/viur-core/blob/96d91c2f5d135c9eeeec68b3b5e20bf4cdefe9f6/src/viur/core/utils/__init__.py#L246) ?

2024-01-29 10:35 UTC, ArneGudermann commented on src/viur/core/render/html/env/viur.py
> +        return ""
```suggestion
        logging.error("No derivation for this fileObj")
        return ""
```

2024-01-30 12:22 UTC, phorward commented
> Thank you @phorward for the PR. I have one more question. Shouldn't we include the functions that are now out of the utils in the [__UTILS_NAME_REPLACEMENT](https://github.com/viur-framework/viur-core/blob/96d91c2f5d135c9eeeec68b3b5e20bf4cdefe9f6/src/viur/core/utils/__init__.py#L246) ?

No, these functions where only used in viur-core itself. Therefore, I don't think it's necessary.

2024-01-30 12:23 UTC, sveneberth approved these changes

2024-01-30 12:53 UTC, ArneGudermann approved these changes

2024-01-30 12:55 UTC, merged