feat: Allow `None` in `skel setBoneValue`
viur-framework/viur-core pull request #1053
Opened 2024-01-31 16:49 UTC by ArneGudermann

Resolves #1047.
@sveneberth  I hope I have understood your issue correctly.  
This PR sets the value of the bones to `None`.

2024-01-31 22:30 UTC, sveneberth submitted a review, later dismissed
Simple solution, thanks

2024-02-01 10:12 UTC, phorward requested changes

2024-02-01 10:12 UTC, phorward commented on src/viur/core/skeleton.py
> +            return True
Doesn't deserialization make sense when not being in the `None`-case? 
```suggestion
        if value is None:
            skelValues[boneName] = None
            return True

        _ = skelValues[boneName]  # ensure the bone is being unserialized first
```

2024-02-02 09:43 UTC, phorward requested changes
I'm sorry, but there are two additional issues regarding this PR:

1. What about the `append`-parameter? IMHO the None-logic should only apply when append is False.
2. What about the `language`-parameter? Can you add additional logic to this, too?

2024-02-02 09:44 UTC, phorward commented
@ArneGudermann can you please re-check the two points stated?

2024-02-02 09:56 UTC, ArneGudermann commented
In #1047 @sveneberth says he want's to clear the bone and I think we should ignore the language and `append`.

2024-02-02 10:37 UTC, phorward commented
> In #1047 @sveneberth says he want's to clear the bone and I think we should ignore the language and `append`.

yeah, in his case calling `skel.setBoneValue("bla", None)`, this should be the case. But in `skel.setBoneValue("bla", None, append=True)` removing previously added data is not right, same as `skel.setBoneValue("bla", None, language="en")`, the caller assumes to clear the "en"-part of the bone only.

Please add these cases appropriately.

2024-02-02 16:26 UTC, sveneberth commented
I think it's good to only clear the value of a language with `lang`. But append `None` I think is basically nonsense and should raise an exception.

2024-02-06 10:51 UTC, phorward requested changes
Hello @ArneGudermann, I'm still a little unhappy with this.

Here's an improved proposal on your PR: https://github.com/ArneGudermann/viur-core/pull/2

This entire function with its ugly name is a mess. `bone.setBoneValue` could also be the place to do it. Nevertheless, I think with my proposal (untested!) this might work better is is more integrative.

In VIUR4, this Gelumpe should be generally revised.

2024-02-06 14:49 UTC, sveneberth requested changes

2024-02-06 14:49 UTC, sveneberth commented on src/viur/core/skeleton.py
> +                skelValues[boneName] = None
Shouldn't this better be a list on multiple bones?
```suggestion
                skelValues[boneName][language] = [] if bone.multiple else None
            else:
                skelValues[boneName] = [] if bone.multiple else None
```

2024-02-27 18:45 UTC, phorward approved these changes

2024-02-27 18:51 UTC, sveneberth approved these changes

2024-02-27 21:00 UTC, merged