refactor: `BaseBone.buildDBSort`
viur-framework/viur-core pull request #1077
Opened 2024-02-23 17:31 UTC by phorward

- Refactored entire code
- Moved language stuff into the `BaseBone`
- Support for better, talking names for "orderdir" parameter
---
Yet untested and wip.

2024-05-24 08:04 UTC, ArneGudermann approved these changes

2024-05-24 14:27 UTC, sveneberth requested changes

2024-05-27 22:51 UTC, phorward commented on src/viur/core/bones/relational.py
> +
```suggestion

```

2024-07-02 13:21 UTC, phorward commented on src/viur/core/bones/base.py
> -                    logging.warning(f"I fixed you query! Impossible ordering changed to {inEqFilter}, {order[0]}")
The `logging.warning` related to this is printed some lines below, but in better Englisch.

2024-07-10 20:20 UTC, sveneberth approved these changes
LGTM

2024-07-10 21:24 UTC, merged