feat: store compute value on unserialize
viur-framework/viur-core pull request #1107
Opened 2024-03-15 14:52 UTC by ArneGudermann

resolves #709

2024-03-15 15:35 UTC, sveneberth requested changes

2024-03-15 15:35 UTC, sveneberth commented on src/viur/core/bones/base.py
> +                        db.RunInTransaction(transact)
```suggestion
                        if db.IsInTransaction():
                            transact()
                        else:
                            db.RunInTransaction(transact)
```

2024-03-15 15:39 UTC, sveneberth commented
But, this does not work for a computed `RelationalBone`, because this is not calling `.serialize()`

2024-03-19 13:29 UTC, sveneberth submitted a review, later dismissed
So far this seems to work, I observe this for bone types and then we can do a follow-up fix.

---

@phorward  Can we move this to [3.6](https://github.com/viur-framework/viur-core/milestone/1)?

2024-04-29 09:52 UTC, phorward commented
> @phorward Can we move this to [3.6](https://github.com/viur-framework/viur-core/milestone/1)?

Is this still valid? IMHO we can do it.

2024-05-22 21:41 UTC, sveneberth approved these changes

2024-06-13 18:36 UTC, phorward approved these changes

2024-06-13 18:37 UTC, merged