feat Add Support for singel value  and __default__ for multi-lang Bones
viur-framework/viur-core pull request #1108
Opened 2024-03-15 15:17 UTC by ArneGudermann

resolves #1096

2024-03-15 15:42 UTC, sveneberth requested changes

2024-03-15 15:42 UTC, sveneberth commented on src/viur/core/bones/base.py
> +                    self.defaultValue |= {lang: defaultValue[lang] for lang in self.languages if lang in defaultValue}
```suggestion
                    self.defaultValue = {lang: defaultValue.get(lang, defaultValue["__default__"]) for lang in self.languages}
```

2024-03-15 16:01 UTC, sveneberth approved these changes

2024-04-29 09:49 UTC, phorward approved these changes

2024-04-29 09:49 UTC, merged