feat Add session `setdefault`
viur-framework/viur-core pull request #1140
Opened 2024-04-11 07:37 UTC by ArneGudermann

Resolves https://github.com/viur-framework/viur-shop/blob/f6e84e772be01d7cf2beb74d674a3aeda6ac303b/src/viur/shop/modules/abstract.py#L45

2024-04-12 13:20 UTC, sveneberth requested changes

2024-04-12 13:20 UTC, sveneberth commented on src/viur/core/session.py
> +        return value
Cloud be more simple, and this returns the correct value if this key was already in the session.
```suggestion
        return self.session.setdefault(key, value)
```

2024-04-16 10:08 UTC, sveneberth approved these changes

2024-04-29 09:37 UTC, phorward approved these changes
It's okay for me. We generally should think about subclassing `Session` from `db.Entity`, which is a subclass of dict, so that the session can be used like an ordinary dict in all situations.

2024-04-29 09:38 UTC, merged