feat: Add serialize_compute and unserialize_compute
viur-framework/viur-core pull request #1145
Opened 2024-04-18 08:37 UTC by ArneGudermann

fix for #1138

2024-05-03 14:19 UTC, sveneberth requested changes

2024-05-03 14:19 UTC, sveneberth commented on src/viur/core/bones/base.py
> +    def serialize_compute(self, skel, name):
```suggestion
    def serialize_compute(self, skel: "SkeletonInstance", name: str) -> None:
```

2024-05-03 14:19 UTC, sveneberth commented on src/viur/core/bones/base.py
> +    def unserialize_compute(self, skel, name, loaded_value):
```suggestion
    def unserialize_compute(self, skel: "SkeletonInstance", name: str, loaded_value: t.Any) -> None:
```

2024-05-17 22:34 UTC, sveneberth commented on src/viur/core/bones/base.py
> +    def unserialize_compute(self, skel: "SkeletonInstance", name: str, loaded_value: t.Any) -> None:
```suggestion
    def unserialize_compute(self, skel: "SkeletonInstance", name: str, loaded_value: t.Any) -> bool:
```

2024-05-17 22:35 UTC, sveneberth submitted a review, later dismissed

2024-09-18 21:57 UTC, phorward requested changes
@ArneGudermann can you please fix the conflicts with the current develop branch, so we can merge this?

2024-09-19 08:59 UTC, phorward requested changes

2024-09-19 08:59 UTC, phorward commented on src/viur/core/bones/base.py
> +        # Handle compute on write
Can you provide an adequate doc-string here?

2024-09-19 08:59 UTC, phorward commented on src/viur/core/bones/base.py
> +        # Is this value computed?
Can you provide an adequate doc-string here?

2024-10-15 10:56 UTC, phorward commented on src/viur/core/bones/base.py
> +
```suggestion
```

2024-10-15 14:28 UTC, sveneberth submitted a review, later dismissed

2024-10-15 14:28 UTC, sveneberth commented on src/viur/core/bones/base.py
> +        :param name: The name of the Bone in the Skeleton
```suggestion
        :param skel: The SkeletonInstance where the current bone is located
        :param name: The name of the bone in the Skeleton
```

2024-10-15 14:28 UTC, sveneberth commented on src/viur/core/bones/base.py
> +        if not self.compute and self._prevent_compute:
The negation of
```py
self.compute and not self._prevent_compute
```


# (
**=**
```py
not (self.compute and not self._prevent_compute)
```
# )
is after de Morgan's laws
```suggestion
        if not self.compute or self._prevent_compute:
```

2024-10-16 06:51 UTC, phorward approved these changes

2024-10-16 07:05 UTC, ArneGudermann commented on src/viur/core/bones/base.py
> +
```suggestion
```

2024-10-16 09:29 UTC, merged