fix: Make `Translation`-module `admin_info` configurable
viur-framework/viur-core pull request #1158
Opened 2024-05-08 13:21 UTC by phorward

Currently, the translation module is shown in every project using viur-core 3.6. By default, it should be non-visible, and at least, it is a part of the admin tool. Nevertheless, the possibility of hiding or entirely omitting it should be given.

2024-05-08 15:00 UTC, sveneberth requested changes

2024-05-08 15:00 UTC, sveneberth commented on src/viur/core/modules/translation.py
> +        if admin_info := conf.translation_admin_info:
If the config is empty (bc I just want to use the config as it is defined in this method) that branch would be skipped.

I think this merging is in general kinda hackish. 

monkeypatching `Translation.adminInfo = { ... }` would btw work as well.

2024-05-13 13:53 UTC, phorward commented on src/viur/core/config.py
> +        "icon": "signpost-2-fill",
There is no `translate` icon in the [ViUR icons set](https://serene-allen-537100.netlify.app/components/icon/#viur-library). The module showed up as a big phat "T", which just looks ugly as its best.

2024-05-13 14:03 UTC, phorward commented
@sveneberth see #[326dd18](https://github.com/viur-framework/viur-core/pull/1158/commits/326dd18ebfd6427ba51583d5cda550394bb71600) for an updated implementation.

2024-05-14 17:50 UTC, sveneberth approved these changes

2024-05-14 19:59 UTC, merged