Change of LICENSE from LGPL into MIT
viur-framework/viur-core pull request #1164
Opened 2024-05-15 15:59 UTC by phorward

In the viur-meeting on 2024-04-12, it was decided to change the licensing terms of the viur-core component from the LGPL-v3 into the MIT license.

This pull request updates all relevant parts of the codebase.

2024-05-15 17:29 UTC, sveneberth requested changes

2024-05-15 17:29 UTC, sveneberth commented on src/viur/core/__init__.py
Maybe it would be not bad to link the docs:
```suggestion

https://core.docs.viur.dev
```

2024-05-15 20:42 UTC, sveneberth approved these changes

2024-05-16 07:59 UTC, ArneGudermann approved these changes

2024-05-16 09:00 UTC, merged