feat: Add hash for Files
viur-framework/viur-core pull request #1180
Opened 2024-06-07 09:05 UTC by ArneGudermann

This PR add the CRC32C and MD5 hash to the File skel. 

Resolves: #1176

2024-06-07 16:58 UTC, sveneberth requested changes
Nice, can you add this in [`write`](https://github.com/viur-framework/viur-core/blob/40d4e8228e72110c69d86ed80e680a55efc64656/src/viur/core/modules/file.py#L603-L633) too?

2024-06-11 22:54 UTC, phorward requested changes
Hello @ArneGudermann, thanks for achieving this issue.

First of all, I would like to refer the hashed value as "checksum" as it should be an indicator for same files, regardless of the filename and the size. 

Then, I'm wondering about the chosen hash algorithms. Why did you chose CRC32c and MD5?

After a little research, I think that SHA-256 would be the best choice for collision resistance. MD5, SHA-1 and CRC32c are not designed for collision resistance. Therefore, I would prefer to only provide a sha256 checksum for all files, and avoid use of two hash algorithms (what's the advantage?). 

I'm open for discussions.

2024-06-11 22:54 UTC, phorward commented on src/viur/core/modules/file.py
> +    )
Can we rename it to checksum to clarify that this feature is used to identify same files?
```suggestion
    crc32c_checksum = StringBone(
        descr="CRC32C checksum",
        readOnly=True,
    )
    md5_checksum = StringBone(
        descr="MD5 checksum",
        readOnly=True,
    )
```

2024-06-11 22:54 UTC, phorward commented on src/viur/core/modules/file.py
> +        skel["md5_hash"] = base64.b64decode(blob.md5_hash).hex()
```suggestion
        skel["crc32c_checksum"] = base64.b64decode(blob.crc32c).hex()
        skel["md5_checksum"] = base64.b64decode(blob.md5_hash).hex()
```

2024-06-11 22:54 UTC, phorward commented on src/viur/core/modules/file.py
> +            skel["md5_hash"] = base64.b64decode(blob.md5_hash).hex()
```suggestion
            skel["crc32c_checksum"] = base64.b64decode(blob.crc32c).hex()
            skel["md5_checksum"] = base64.b64decode(blob.md5_hash).hex()
```

2024-06-12 07:47 UTC, ArneGudermann commented
@phorward i used [md5](https://cloud.google.com/python/docs/reference/storage/latest/google.cloud.storage.blob.Blob#google_cloud_storage_blob_Blob_md5_hash) and  [crc32c](https://cloud.google.com/python/docs/reference/storage/latest/google.cloud.storage.blob.Blob#google_cloud_storage_blob_Blob_crc32c) because they are the only two that are provided by google storage. otherwise we would have to download the whole blob and hash it ourselves.

2024-06-13 17:59 UTC, phorward approved these changes
IMHO, we can use this for now.

2024-06-14 21:28 UTC, sveneberth approved these changes

2024-06-15 08:03 UTC, merged