feat: Add charset  `v_func` for `StringBone`
viur-framework/viur-core pull request #1183
Opened 2024-06-07 16:19 UTC by ArneGudermann

Replacement for #1141

2024-06-07 17:03 UTC, sveneberth approved these changes

2024-06-10 20:43 UTC, phorward requested changes
Hello @ArneGudermann, this looks good, can you please provide a docstring with an example as well?

2024-06-11 19:44 UTC, phorward requested changes
@ArneGudermann can you provide an example definition for a `StringBone` that uses the `v_func_valid_chars`-feature? Then, developers can directly abstract the code for their specific use-case and the feature will be used with ease.

2024-06-11 19:44 UTC, phorward commented on src/viur/core/bones/string.py
> +        If not all characters are valid, it returns an error Message.
```suggestion
        Returns a function that takes a string and checks whether it contains valid characters.
        If all characters of the string are valid, it returns None, and succeeds.
        If invalid characters are present, it returns an appropriate error message.
```

2024-06-12 14:00 UTC, sveneberth approved these changes

2024-06-12 14:02 UTC, phorward requested changes
Still missing an example in the docstring!

2024-06-12 14:47 UTC, ArneGudermann commented
@phorward now ok ?

2024-06-12 16:09 UTC, merged