feat: Add `sorted` feature to `MultipleConstraints`
viur-framework/viur-core pull request #1186
Opened 2024-06-10 14:59 UTC by ArneGudermann

Resolves #1185

2024-06-10 20:39 UTC, phorward requested changes
Thanks for this first quick draft on #1185.

Can you please provide a way to allow for reversed sorting as well? I think this should be another member of `MultipleConstraints`. See [here](https://docs.python.org/3/library/functions.html#sorted) for details.

2024-06-11 08:09 UTC, phorward commented on src/viur/core/bones/base.py
> +    sorted_reversed: bool = False
```suggestion
    reverse: bool = False
```

2024-06-11 08:59 UTC, phorward approved these changes

2024-06-11 12:10 UTC, sveneberth approved these changes

2024-06-11 19:45 UTC, merged