fix: render structure on first list (improvement of #774)
viur-framework/viur-core pull request #1189
Opened 2024-06-13 23:24 UTC by phorward

This improves #774, and renders the structure on calls without cursor, so legacy systems can work better with it and still use the feature.

2024-06-14 21:35 UTC, sveneberth requested changes
huh? That's exactly the point of the compatibility mode (yes, I've seen that it's only about the first batch).
But now you are reactivating exactly what we have abolished: the structure is rendered with every first list request. Regardless of whether I make several search requests one after the other or the structure doesn't interest me at all.
I am against this change. 

<sub>(I do not request a change, I want to leave it as it is)</sub>

---

**Edit:** We could make this controllable via an input parameter. e.g. via context variable `@include_structure=True` or via a header `X-Include-Structure: True`.

2024-06-15 08:42 UTC, phorward commented
> **Edit:** We could make this controllable via an input parameter. e.g. via context variable `@include_structure=True` or via a header `X-Include-Structure: True`.

What do you think about a general feature to provide X-ViUR-Structure-header to obtain the structure in any call? This also relates to view/edit/add/clone and other actions.

2024-07-15 13:30 UTC, sveneberth commented
> > **Edit:** We could make this controllable via an input parameter. e.g. via context variable `@include_structure=True` or via a header `X-Include-Structure: True`.
> 
> What do you think about a general feature to provide X-ViUR-Structure-header to obtain the structure in any call? This also relates to view/edit/add/clone and other actions.

Would be nice.

But to make this working on vue.js development server (sending headers in a browser to another server than the current host), we need to support preflight CORS requests. I'd already some issues in other use-cases, so I've started #1215.

2024-07-19 11:31 UTC, phorward commented
We should switch to separation of structure and data fetching, but we should modify cache header so that structure requests are being cached for a specific amount of time. We can think about a decorator for setting a cache-time.

2024-09-30 20:25 UTC, phorward commented
This relates to #1273.

2024-10-16 06:54 UTC, phorward commented
Closing this for now due to irrelevancy.

2024-10-16 06:54 UTC, closed without merging