refactor: Send emails from `EmailTransport` instances instead of class
viur-framework/viur-core pull request #1250
Opened 2024-08-28 19:55 UTC by sveneberth

This allows to store the credentials and other settings on the instance itself and reduce the config size.
Furthermore I think this is more pythonic, combines what belongs together and makes `abc` meaningful.

This a small **breaking change**.
Instead of 
```py
conf.email.mailjet_api_key = secret.get("api-mailjet-key")
conf.email.mailjet_api_secret = secret.get("api-mailjet-secret")
conf.email.transport_class = EmailTransportMailjet
```

you write now
```py
conf.email.transport_class = EmailTransportMailjet(
    api_key=secret.get("api-mailjet-key"),
    secret_key=secret.get("api-mailjet-secret"),
)
```

--- 
### Furthermore 
* Enforce pep8 compliant `snake_case` names as requested by @phorward 
* `email.sendEMail` is now `email.send_email`
* `email.sendEMailToAdmins` is now `email.send_email_to_admins`
* We use the [`deprecated`](https://deprecated.readthedocs.io/en/latest/) package, which is not working smooth as expected, but this can be done later ...
* Add and update a bunch of documentation
* Fixing not used `max_retries` variable
* Introduce some constants (so things can be changed with monkey patching or are clearly reserved and fixed names)

Resolves #813

2024-08-29 11:52 UTC, phorward requested changes
This pull request is in conflict with #1249, can you please integrate it here and fix the config first? IMHO we can make this into core-3.7.

Can you also generally rename the methods to become pep8-compliant, so that splitAddresses becomes split_addresses, etc.

2024-08-30 10:54 UTC, sveneberth commented
> This pull request is in conflict with #1249, can you please integrate it here and fix the config first

Yeah, I expected this. 

I will resolve the conflicts and do the renamings later.

2024-08-30 14:59 UTC, sveneberth commented
@phorward @ArneGudermann @KadirBalku I'm now done, you can review now :)

2024-08-30 15:53 UTC, phorward approved these changes

2024-09-02 11:07 UTC, merged