fix: handle gracefully downloadurls and srcsets with optional languages overwrite for files
viur-framework/viur-core pull request #1266
Opened 2024-09-24 18:44 UTC by skoegl

See #1265

2024-09-24 19:26 UTC, phorward requested changes
Hello @skoegl, thanks for creating this pull request.
Can you please test me suggested changes and apply it to the case below as well?

2024-09-24 19:26 UTC, phorward commented on src/viur/core/modules/file.py
> +        language: t.Optional[str] = None
```suggestion
        language: t.Optional[str] = None,
```

2024-09-24 19:26 UTC, phorward commented on src/viur/core/modules/file.py
> +                file = file[conf.i18n.default_language]
This should satisfy already, and returns empty when no language is given, but it is a LanguageWrapper.

```suggestion
            language = language or current.language.get()
            if not language or not (file := file.get(language)):
                return ""
```

The additional check on `conf.i18n.default_language` is already handled by `current.language.get()`, as this ContextVar is initialized with `conf.i18n.default_language` on request processing.

2024-09-24 19:26 UTC, phorward commented on src/viur/core/render/html/env/viur.py
> +    language: t.Optional[str] = None
```suggestion
    language: t.Optional[str] = None,
```

2024-09-24 19:26 UTC, phorward commented on src/viur/core/render/html/env/viur.py
> +            fileObj = fileObj[conf.i18n.default_language]
Same as above.

2024-09-24 19:26 UTC, phorward commented on src/viur/core/render/html/env/viur.py
> +    language: t.Optional[str] = None
```suggestion
    language: t.Optional[str] = None,
```

2024-09-27 14:30 UTC, skoegl commented
Thank you for the code review . I hopefully have completed all requested changes. Please take another look and if ok, please merge.

2024-09-30 09:00 UTC, phorward approved these changes

2024-09-30 18:50 UTC, merged