feat: Add callable for BooleanBone
viur-framework/viur-core pull request #1274
Opened 2024-09-27 13:42 UTC by ArneGudermann

Fix for #1178

and add check for  values in getdefaultValue.

2024-09-30 09:06 UTC, phorward requested changes

2024-09-30 09:06 UTC, phorward commented on src/viur/core/bones/base.py
> +            raise ValueError(f"Callable default values must have at least 2 Parameters for 'skel' and 'self'")
Is this check really necessary, or shall we rely on the type annotations and let Python do the exception raise on error?

```suggestion
            raise ValueError(f"Callable default values require for two parameters (self and skel)")
```

2024-09-30 21:55 UTC, phorward submitted a review, later dismissed

2024-10-01 15:09 UTC, sveneberth requested changes

2024-10-01 15:09 UTC, sveneberth commented on src/viur/core/bones/boolean.py
> +                                "can be provided as BooleanBone defaultValue")
This does not work for me:
```py
    test_boolean_callable_single_lang1 = BooleanBone(
        defaultValue=lambda skel, bone: print(skel["key"], bone.descr) or bool(random.randint(0,1)),
    )
    test_boolean_callable_multi_lang1 = BooleanBone(
        languages=["de", "en", "fr"],
        defaultValue=lambda skel, bone: print(skel["key"], bone.descr) or bool(random.randint(0,1)),
    )
    test_boolean_callable_multi_lang2 = BooleanBone(
        languages=["de", "en", "fr", "nl"],
        defaultValue=lambda skel, bone: {"de": True, "en": False, "fr": None},
    )
```



```
    test_boolean_callable_single_lang1 = BooleanBone(
                                         ^^^^^^^^^^^^
  File "/home/.../deploy/viur/core/bones/boolean.py", line 29, in __init__
    raise TypeError("Only 'True', 'False', 'None' or 'callable' "
TypeError: Only 'True', 'False', 'None' or 'callable' can be provided as BooleanBone defaultValue
```


---
Shouldn't this be

```suggestion
            if not kwargs.get("languages") and not (isinstance(defaultValue, bool) or callable(defaultValue)):

```

2024-10-08 22:55 UTC, sveneberth requested changes

2024-10-08 22:55 UTC, sveneberth commented on src/viur/core/bones/boolean.py
> +                raise TypeError("Only 'True', 'False' , 'None' or callable can be provided as BooleanBone defaultValue")
The quotes may be misleading: It must be a string.
```suggestion
                raise TypeError("Only True, False, None or callable can be provided as BooleanBone defaultValue")
```

2024-10-09 09:53 UTC, phorward approved these changes

2024-10-09 22:46 UTC, merged