feat: Add downloadUrl for derives
viur-framework/viur-core pull request #1290
Opened 2024-10-21 16:04 UTC by ArneGudermann

Fix for https://github.com/viur-framework/viur-core/issues/506

2024-10-21 16:49 UTC, phorward requested changes

2024-10-21 16:49 UTC, phorward commented on src/viur/core/config.py
> +        conf.file_generate_download_url_for_derives = ["test.image*"]
```suggestion
    If True, for all derives, a download URL is created as well.
    
    When an iterable of str is provided, for all entries that match a pattern,
    a download URL will be created.

    Example:
    ```py
        class Test(Skeleton):
            image_bar = FileBone(derive=conf["derives"])
            image_foo = FileBone(derive=conf["derives"])
            logo = FileBone(derive=conf["derives"])

        conf.file_generate_download_url_for_derives = ["test.image*"]
    ```
```

2024-10-21 16:49 UTC, phorward commented on src/viur/core/config.py
> +    file_generate_download_url_for_derives: bool | list[str] = False
```suggestion
    file_generate_download_url_for_derives: bool | t.Iterable[str] = False
```

2024-10-21 16:49 UTC, phorward commented on src/viur/core/render/json/default.py
> +                if isinstance(conf.file_generate_download_url_for_derives, list):
```suggestion
                if isinstance(conf.file_generate_download_url_for_derives, t.Iterable):
```

2024-10-21 16:49 UTC, phorward commented on src/viur/core/render/json/default.py
> +                    search_path.append("*")
Typo???
```suggestion
                    search_paths.append("*")
```

2024-10-23 14:05 UTC, sveneberth commented on src/viur/core/render/json/default.py
> -            res["downloadUrl"] = file.create_download_url(
This is the opposite of #1252, I would keep it as it is.

2024-10-23 14:22 UTC, sveneberth commented on src/viur/core/render/json/default.py
> +                search_paths.append(search_path)
If you provide this header multiple times gunicorn merge it comma seperated into one, so we should use split to support it too:


```suggestion
            if search_path := current.request.get().request.headers.get("X-VIUR-DERIVED-DOWNLOAD-URL"):
                search_paths.extend(search_path.split(","))
```

2024-10-28 20:28 UTC, phorward commented
Currently replaced by #1305 due heavy runtime impact.

2025-07-10 13:09 UTC, closed without merging