refactor: File-module reference should use instance
viur-framework/viur-core pull request #1293
Opened 2024-10-22 14:09 UTC by bb-mausbrand

staticmethods in File using File converted to classmethods using cls
external references to File replaced with conf.main_app.file

2024-10-22 15:56 UTC, sveneberth requested changes

2024-10-22 15:56 UTC, sveneberth commented on src/viur/core/modules/file.py
> +            "GOOGLE_STORAGE_BUCKET": ("viur.core.config.get_bucket()", _private_bucket),
```suggestion
            "GOOGLE_STORAGE_BUCKET": ("conf.main_app.file.get_bucket()", _private_bucket),
```

2024-10-23 14:04 UTC, sveneberth submitted a review, later dismissed

2025-05-08 07:10 UTC, phorward approved these changes

2025-05-08 07:11 UTC, phorward commented on src/viur/core/modules/file.py
> +
Part was moved.
```suggestion
```

2025-05-08 07:13 UTC, merged