feat: extend the write()-method of File to accept a rootnode and foldername
viur-framework/viur-core pull request #1308
Opened 2024-10-30 10:21 UTC by bb-mausbrand

feat: extend the write()-method of File to accept a rootnode and foldername

2024-10-30 22:53 UTC, sveneberth requested changes

2024-10-30 22:53 UTC, sveneberth commented on src/viur/core/modules/file.py
> +            fileskel["pending"] = False
Shouldn't `fileskel["pending"] = False` always be the case here in write? The "upload" is done at once.

```suggestion
```

2024-10-30 22:53 UTC, sveneberth commented on src/viur/core/modules/file.py
> +
```suggestion
            fileskel["pending"] = False

```

2024-11-06 20:59 UTC, sveneberth approved these changes

2024-11-07 08:27 UTC, ArneGudermann approved these changes

2024-11-11 22:15 UTC, phorward requested changes
Looks good already, mostly some cosmetics.

2024-11-20 20:05 UTC, sveneberth requested changes

2024-11-20 20:05 UTC, sveneberth commented on src/viur/core/modules/file.py
> +                foldernames = foldernames.replace('\\', '/')
Since this `write` method is only for internal usage and we don't expect pathes from client users I don't see the necessity of it.

2025-07-08 18:57 UTC, merged