Feature/hooks before actions
viur-framework/viur-core pull request #147
Opened 2020-10-14 16:58 UTC by phorward

Additionally to the **onAdded**, **onEdited**, **onDeleted** hooks, this pull request introduces further hooks called before the specific database operation is performed, using **onAdd**, **onEdit** and **onDelete**.
Furthermore **onViewed** has been renamed to **onView** because the hook is performed before the operation takes place.

2020-10-14 17:34 UTC, sveneberth commented on prototypes/singleton.py
> +		logging.debug("onView")
I think this will spam the logs :/

2020-10-14 17:36 UTC, sveneberth commented on prototypes/list.py
> +		logging.debug("onView")
I think this will spam the logs :/

2020-10-14 17:37 UTC, sveneberth requested changes

2020-10-14 17:37 UTC, sveneberth commented on prototypes/singleton.py
> +		logging.debug("onView")
this as well

2020-10-14 17:37 UTC, sveneberth commented on prototypes/tree.py
> +		logging.debug("onView")
this as well

2020-10-14 17:37 UTC, sveneberth commented on prototypes/list.py
> +		logging.debug("onView")
I think this will spam the logs :/

2020-10-19 13:18 UTC, tsteinruecken commented
I don't mind. For view it's probably better to remove the logging; but add/edit/deletion isn't that common...

2020-10-19 13:47 UTC, phorward commented
All loggings had been replaced by passes.

2020-10-20 13:08 UTC, sveneberth approved these changes

2020-10-21 20:31 UTC, merged