Implement verbose error page mode
viur-framework/viur-core pull request #368
Opened 2022-03-02 20:12 UTC by sveneberth

Display several meta information of the current request, session and environment on the error page for faster debugging.
Can be enabled by setting `conf[viur.debug.verboseErrorHandler"]` to `True`.

I changed the error.css a bit to support larger content and the new content. Because afaik a new design is already in the pipeline, this is only very rudimentary.

![Screenshot](https://user-images.githubusercontent.com/10272292/156441385-21f31c2e-bf43-45eb-be4f-26f40a661bbc.png)

2022-03-02 23:26 UTC, sveneberth commented on core/request.py
> +					if not isinstance(e, errors.HTTPException):
@viur-framework/developers What do your think about this. Shall we print a traceback on `HTTPException`s or not? Might be helpful to find the right case, if there are multiple reasons.

2022-03-03 08:47 UTC, tsteinruecken commented
I'm undecided about this one. I generally like the idea of a better error page, however i see a few problems with this approach.
1) Remove that config switch. Make this the default for local development and keep it disabled if deployed. Someone will forget to turn this switch back of when deploying - causing probably sensitive information to leak.
2) None of the information added has any additional value for the developer. You really know the state of your session, the parameters supplied, your python version and so on (or can very easily retrieve these information from your browser / environment etc). But what we could do is collecting all the logs that have been generated by that request that lead to the exception (at least the ViUR ones) - because this information is usually swamped out by all the logs the dev_appserver / google api calls generated.
3) Ignore httpErrors - unless traceExceptions is set. That flag is explicitly for debugging these.

2022-04-27 09:59 UTC, phorward commented
Hello @sveneberth, I'm in the opinion this feature is useful and should be integrated somehow. Can you please update your pull request to current main, or provide a similar solution in viur-base?

2022-04-27 11:30 UTC, phorward requested changes
Please see previous comment.

2022-06-23 14:53 UTC, phorward commented
As there is no more interaction here, the ticket will be closed.
It cannot be merged in this way, but a verbose and nice error reporting would be great.
Please see my [comments](https://github.com/viur-framework/viur-core/pull/368#issuecomment-1110809499) on this in here and create a different approach based on the work done here. Thanks.

2022-06-23 14:53 UTC, closed without merging