Feature/viur datastore versionbump 1.2.2
viur-framework/viur-core pull request #425
Opened 2022-04-24 20:59 UTC by skoegl

2022-04-25 04:12 UTC, XeoN-GHMB commented
please update, also the setup.cfg

2022-04-25 04:14 UTC, XeoN-GHMB requested changes
please update, also the setup.cfg

2022-04-25 19:11 UTC, phorward submitted a review, later dismissed

2022-04-26 03:36 UTC, XeoN-GHMB approved these changes

2022-04-26 12:13 UTC, merged