Set the cursor of the next chunk on the query
viur-framework/viur-core pull request #438
Opened 2022-05-13 20:36 UTC by sveneberth

2022-05-16 07:59 UTC, phorward commented on CHANGELOG.md
> +- Set the cursor of the next chunk on the query in `securitykey.doClearSKeys()`
Hello, thanks for doing this, but in future we gonna generate Changelogs from the git history, which is nice due the squashed commits.

2022-05-16 08:01 UTC, phorward commented on core/securitykey.py
> +	if cursor is not None:
you can call setCursor with a None-value as will, with the same effect.

2022-05-16 08:04 UTC, phorward requested changes
Hello @sveneberth, thanks for this PR. Can you please check the indentation, it seems there is a mess-up with tabs and spaces. Turn it into tabs first, we convert them later in a separate PR.

2022-05-16 08:32 UTC, tsteinruecken commented
I'd suggest removing the cursor parameter altogether. We delete the entities we hit - so there's no need to advance the query with a cursor.

2022-05-16 08:44 UTC, phorward commented
> I'd suggest removing the cursor parameter altogether. We delete the entities we hit - so there's no need to advance the query with a cursor.

I'm complying with this suggestion, please remove the cursor entirely.

2022-05-17 16:18 UTC, sveneberth commented
> Hello @sveneberth, thanks for this PR. Can you please check the indentation, it seems there is a mess-up with tabs and spaces. Turn it into tabs first, we convert them later in a separate PR.

I don't see any indentation issues?!

2022-05-17 16:18 UTC, sveneberth commented
> I'd suggest removing the cursor parameter altogether. We delete the entities we hit - so there's no need to advance the query with a cursor.

Done

2022-05-17 19:53 UTC, phorward requested changes
I still found one more little issue. I think we generally should fix this in viur-datastore and remove all keysOnly-parameters which don't have any effect (there are some places). I've opened issue https://github.com/viur-framework/viur-datastore/pull/6 to fix this as well.

2022-05-17 19:53 UTC, phorward commented on core/securitykey.py
>  	for oldKey in query.run(100, keysOnly=True):
keysOnly=True doesn't have any effect in viur-datastore, and is just thrown away by kwargs.
```suggestion
	for oldKey in query.run(100):
```

2022-05-19 11:52 UTC, phorward approved these changes

2022-05-19 11:52 UTC, merged