Fixing file module
viur-framework/viur-core pull request #454
Opened 2022-05-30 10:16 UTC by phorward

Due the renaming of bones.stringBone into bones.string, the stdlib `import string` and then `from viur.core.bones import *` afterwards causes the assert with string.ascii_digits etc. to fail.

This fixes it entirely and cleans up Skeleton definition of the file module generally (formatting, index=True removal)

2022-05-30 10:23 UTC, Xeon2003 approved these changes

2022-05-30 10:24 UTC, XeoN-GHMB approved these changes

2022-05-31 16:37 UTC, sveneberth requested changes
Instead of importing the _bones_ module, you could just import the bones needed. This would only be a Oneliner-fix and doesn't require the attribute access `bones.XYZBone`.

```py
from from viur.core.bones import BaseBone, BooleanBone, KeyBone, NumericBone, StringBone
```

2022-05-31 21:27 UTC, phorward commented
> Instead of importing the _bones_ module, you could just import the bones needed. This would only be a Oneliner-fix and doesn't require the attribute access `bones.XYZBone`.
> 
> ```python
> from viur.core.bones import BaseBone, BooleanBone, KeyBone, NumericBone, StringBone
> ```

You're right as well. Next to your change, I've added another proposal, please review. Both should work.

2022-06-01 20:53 UTC, sveneberth requested changes

2022-06-01 20:53 UTC, sveneberth commented on core/bones/__init__.py
> +from .base import BaseBone, ReadFromClientError, UniqueValue, UniqueLockMethod, MultipleConstraints
```suggestion
from .base import BaseBone, ReadFromClientError, ReadFromClientErrorSeverity, UniqueValue, UniqueLockMethod, MultipleConstraints
```

2022-06-01 20:53 UTC, sveneberth commented on core/bones/__init__.py
> +	"ReadFromClientError",
```suggestion
	"ReadFromClientError",
	"ReadFromClientErrorSeverity",
```

2022-06-02 12:25 UTC, merged