Add support for `Literal` type annotations in processTypeHint
viur-framework/viur-core pull request #457
Opened 2022-06-03 19:58 UTC by sveneberth

Parse also `Literal` type annotains in exposed methods.
Literals were introduced with PEP-586 for Python >= 3.8.

Example:
```py
@exposed
def my_method(self, value: Literal['a', 'b', 7]):
    ...
```
Only 'a', 'b' and 7 are allowed for `value`. Other values will be rejected.
The 7 will be accepted as str, but forwarded as int.

2022-06-07 07:06 UTC, tsteinruecken approved these changes

2022-06-20 10:28 UTC, phorward approved these changes

2022-06-20 10:38 UTC, phorward requested changes
@sveneberth can you please merge current develop into this branch? Features should generally  be made against the develop branch, bug/hotfixes against main. Thanks!

2022-06-20 10:41 UTC, phorward approved these changes
OK nevermind. As #458 relies on this PR, and #458 cannot be merged into develop without huger changes, I'll do it this way now and we merge into main. Next time please do it only on develop.

2022-06-20 10:41 UTC, merged