fixed getReferencedBlobs of textBone so it allows multiple=True data …
viur-framework/viur-core pull request #490
Opened 2022-08-19 15:51 UTC by Grashalmbeisser

…to be saved

2022-08-23 14:13 UTC, sveneberth requested changes
LGTM. The case multiple + languages (`if self.multiple and self.languages:`...) is also missing, can you add it?

2022-09-05 07:07 UTC, XeoN-GHMB approved these changes
As a quick fix okay. Please create a new issue for the case multiple + languages.

2022-09-08 10:07 UTC, phorward approved these changes
Quick fix, improved implementation will follow later on.

2022-09-09 11:38 UTC, sveneberth approved these changes

2022-09-09 13:50 UTC, merged