Re-enabling translations in VIUR3
viur-framework/viur-core pull request #491
Opened 2022-08-24 22:00 UTC by phorward

Maybe this is still a work-in-progress, but IMHO it improves many things not working currently.

- Set currentLanguage based on `conf["viur.defaultLanguage"]`
- Use static translations from the `language` module again
- Translate `SelectBone` values
- Improved `translate`-class to fallback to original key in case no translation is found
- Fixed imports to be more clear
- Fixed translation of exception messages (which works!)

![image](https://user-images.githubusercontent.com/16870072/186531331-ce8af351-9cb7-4086-b6e1-dbddbd5b9864.png)

2022-08-26 10:21 UTC, sveneberth requested changes
Hey @phorward, in General im fine with your changes. But I don't get the reason behind the changed imports. I think it's a kind of personal preference, but I like the shorter `from xy import name` rather than `import xy` with the dot-notation in usage (except it's very vulnerable for conflicts). Anyway, we should follow a consistent style. Maybe it's time to create a ViUR style guide. Otherwise the next person change the imports back.

2022-09-01 22:14 UTC, phorward commented on core/i18n.py
> +import jinja2.ext as jinja2
I was unable to just `import jinja2` and then use `jinja2.ext.Extension` and `jinja2.ext.nodes`, therefore this way.
Its IMHO better than just provide `Extension` and `nodes` on global level.

2022-09-05 07:07 UTC, XeoN-GHMB approved these changes

2022-09-05 07:10 UTC, XeoN-GHMB commented
The core will be reformatted soon, so we should create a viur style guide.

2022-09-05 08:11 UTC, phorward commented on core/i18n.py
> +import jinja2.ext as jinja2
> The core will be reformatted soon, so we should create a viur style guide.

https://github.com/viur-framework/viur-core/pull/491#issuecomment-1236618894

2022-09-07 21:38 UTC, merged