Set new max Value for SortIndexBone
viur-framework/viur-core pull request #499
Opened 2022-09-07 16:54 UTC by ArneGudermann

This pull request set the max value for a SortIndexBone higher, because the UINX timestamp is lager than 2^30.

2022-09-07 17:01 UTC, sveneberth reviewed
I think this could be interesting for the [`NumericBone`](https://github.com/viur-framework/viur-core/blob/222de3385885b80c23c954d60788860b40194c33/core/bones/numeric.py#L20-L21) as well.
I suggest to change the `min` and `max` there and remove the `max` parameter from the `SortIndexBone` because it has the same value anyway.

2022-09-07 17:23 UTC, sveneberth requested changes

2022-09-07 17:23 UTC, sveneberth commented on core/bones/sortindex.py
> +import time, typing,sys
This is no longer necessary.

```suggestion
import time, typing
```

2022-09-07 17:25 UTC, sveneberth approved these changes

2022-09-07 20:56 UTC, phorward submitted a review, later dismissed
Hello @ArneGudermann and @sveneberth I'm also fine with this solution!

2022-09-07 21:05 UTC, phorward commented
Wait a sec... I still have one blur with this issue before merging.

What is the maximum value that can be stored to datastore currently? We need to affirm on this as well, because Python uses some kind of BigInt implementation and can story integer values of arbitrary size. Therefore, I'm sure that there is a limit for numbers.

We first need to find out on our own, or find a valid source about these limits.

2022-09-07 21:06 UTC, phorward commented
We also need to discuss where the limits are with other databases, which is a planned feature.

2022-09-08 06:15 UTC, ArneGudermann commented
The value for sys.maxsize is max 2^63 for a 64 bit system. (https://www.geeksforgeeks.org/sys-maxsize-in-python/)

The datastore can store up to 2^64 bit for int and float. (https://cloud.google.com/datastore/docs/concepts/entities#integer)

MongoDB can also store Long values (https://www.mongodb.com/docs/mongodb-shell/reference/data-types/)

I think all Databases can store numeric values up to 2^64 bit.

2022-09-08 09:02 UTC, phorward commented
@ArneGudermann thanks for clarification.

I've made an improvement to this PR in 24c1c5dbf133d6d0a87e6c08ad7984ae8f676828. Can you please check this out? It avoids setting min or max to something which beyond the system limits. There might also be more constraints, e.g. that min may not be greater than max, or a maximum for precision, but this would blow up the code in here. For me, it is important that no higher limits than the maximums can be set.

2022-09-08 12:54 UTC, merged