SpatialBone Checks
viur-framework/viur-core pull request #507
Opened 2022-09-13 17:06 UTC by ArneGudermann

Checks if boundsLat boundsLat are valid values.
See https://docs.mapbox.com/help/glossary/lat-lon/

Set boundsLat,boundsLat in the renderBoneStructure.

2022-09-13 17:50 UTC, phorward requested changes
Little fix, rest looks OK to me :+1:

2022-09-13 17:50 UTC, phorward commented on core/bones/spatial.py
> +        """
Can we turn this into a standard comment?
```suggestion
        # Checks if boundsLat and boundsLng have possible values
        # See https://docs.mapbox.com/help/glossary/lat-lon/
```

2022-09-13 21:49 UTC, phorward approved these changes

2022-09-14 10:22 UTC, sveneberth requested changes

2022-09-14 10:22 UTC, sveneberth commented on core/bones/spatial.py
> +        assert boundsLng[1] >= -180 and boundsLng[1] <= 180, "boundsLng[1] must be between -180 and 180"
I think, as in some other places in ViUR, the use of `assert` is wrong here. `assert` is a statement for debugging purposes and making internal assumptions, not for validating method arguments.

```suggestion
        if not -90 <= boundsLat[0] <= 90:
			raise ValueError(f"boundsLat[0] must be between -90 and 90. Got {boundsLat[0]!r}")
        if not -90 <= boundsLat[1] <= 90:
			raise ValueError(f"boundsLat[1] must be between -90 and 90. Got {boundsLat[1]!r}")
        if not -180 <= boundsLng[0] <= 180:
			raise ValueError(f"boundsLng[0] must be between -180 and 180. Got {boundsLng[0]!r}")
        if not -180 <= boundsLng[1] <= 180:
			raise ValueError(f"boundsLng[1] must be between -180 and 180. Got {boundsLng[1]!r}")
```

For reference:
https://docs.python.org/3/reference/simple_stmts.html#assert
https://dbader.org/blog/python-assert-tutorial

2022-09-14 12:58 UTC, sveneberth approved these changes

2022-09-14 14:44 UTC, merged