Get project zone from metadata.google.internal
viur-framework/viur-core pull request #519
Opened 2022-09-26 16:14 UTC by ArneGudermann

Get now the project zone from the google metadata server.

https://cloud.google.com/appengine/docs/standard/python3/runtime#metadata_server

2022-09-27 19:46 UTC, phorward requested changes
Hello @ArneGudermann,
thank you, this is an interesting approach, and as long as we resist on Google App Engine I think this is useful. Anyway, we should discuss it in the VIUR meeting on friday. Nevertheless, please have a look at my suggestion.

2022-09-27 19:46 UTC, phorward commented on core/tasks.py
> +        logging.warning("Can't get the queueRegion from the MetaData Server")
Can you please provide a hint why the connection to MetaData server failed?

Here's a suggestion:
```suggestion
    except Exception as e:  # Something went wrong with the Google Metadata Sever we use the old way
        logging.warning(f"Can't obtain queueRegion from Google MetaData Server due exception {e=}")
```

2022-09-27 20:06 UTC, phorward approved these changes
I'm fine with it, but we should wait until friday. Thanks!

2022-09-30 17:05 UTC, sveneberth requested changes

2022-09-30 17:05 UTC, sveneberth commented on core/tasks.py
> +        queueRegion = "-".join(r.text.split("/")[-1].split("-")[:2])
You can save the join:
```suggestion
        queueRegion = r.text.split("/")[-1].rsplit("-", 1)[0]
```

2022-10-01 18:38 UTC, phorward approved these changes

2022-10-01 18:38 UTC, merged