Feature/pep8localcheck
viur-framework/viur-core pull request #539
Opened 2022-11-02 12:41 UTC by Grashalmbeisser

I added an tox.ini for the viur core project in which u can setup ur pep8 preferences
also a pep8 checker command in the Pipfile "pep8check" which allows u to check only ur diffed files.

It runs with `pipenv run pep8check`

2022-11-02 12:54 UTC, sveneberth requested changes

2022-11-02 12:54 UTC, sveneberth commented on tox.ini
> +show-pep8 = True
Please use 
```ini
show-pep8 = False
```

2022-11-02 12:56 UTC, Grashalmbeisser commented on tox.ini
> +show-pep8 = True
the change was implemented

2022-11-02 13:10 UTC, sveneberth approved these changes

2022-11-02 13:51 UTC, sveneberth approved these changes
Sorry for my latest commits...

2022-11-02 14:04 UTC, sveneberth requested changes
This PR no longer makes sense as it is, since pep8speaks has stopped working. We have to find another runner or reduce this PR to the pycodestyle config.

See https://github.com/OrkoHunter/pep8speaks/issues/189#issuecomment-1267106628

2022-11-02 17:46 UTC, sveneberth approved these changes

2022-11-08 13:17 UTC, phorward approved these changes

2022-11-08 13:17 UTC, merged