Feature/pep8enforcing
viur-framework/viur-core pull request #540
Opened 2022-11-02 16:34 UTC by Grashalmbeisser

@sveneberth and i added a Github action, which test for propper pep8 usage

2022-11-02 17:52 UTC, sveneberth requested changes

2022-11-02 17:52 UTC, sveneberth commented on .github/workflows/pep8.yaml
> +name: PEP8
I think that name would be a little more precise.
```suggestion
name: PEP8 linter
```

2022-11-04 12:45 UTC, sveneberth approved these changes

2022-11-08 13:16 UTC, phorward approved these changes

2022-11-08 13:16 UTC, merged