Make the Password Bone more  configurable
viur-framework/viur-core pull request #619
Opened 2023-01-17 13:03 UTC by ArneGudermann

Hello everyone,
This PR make the password Bone more configurable. You can now set:

- The min length of the password
- The threshold for tests to pass
- What tests the password must passesd

2023-01-17 13:19 UTC, phorward requested changes

2023-01-17 13:41 UTC, phorward commented on core/bones/password.py
> +        super(PasswordBone, self).__init__()
super-parameters can be omitted.
```suggestion
        super().__init__()
```

2023-01-17 13:42 UTC, phorward requested changes
one little fix?

2023-01-17 13:43 UTC, phorward submitted a review, later dismissed

2023-01-17 18:39 UTC, sveneberth requested changes
Why not a logics expression as written in the developers chat?



```py
password_test = """sum([
    val.lower() != val,
    val.upper() != val,
    any([x in val for x in "0123456789"]),
    any([x not in ("abcdefghijklmnopqrstuvwxyz0123456789") for x in val.lower()]),
]) > 3"""

logics = Logics(password_test)
print(logics.run({"val": the_password))
```


Not tested, because I cat't get logics to work standalone on my machine :/.
But this could be evaluated by the core and vi and customized - if necessary.

2023-01-18 08:42 UTC, phorward commented
> Why not a logics expression as written in the developers chat?

I'm a fan of it, but not within this pull request.

2023-01-18 09:15 UTC, ArneGudermann commented
I haven't used `logics-py` because I don't think it's adjustable enough or I don't know enough about it. If I want to use the password bone for some kind of **pin** input then I want to set the length to 4 for example and only allow numbers. Or I want that all 4 conditions in the password are fulfilled then I must write this also again differently.

2023-01-18 11:03 UTC, phorward commented
> I haven't used `logics-py` because I don't think it's adjustable enough or I don't know enough about it. If I want to use the password bone for some kind of **pin** input then I want to set the length to 4 for example and only allow numbers. Or I want that all 4 conditions in the password are fulfilled then I must write this also again differently.

Sure, you can express all this in Logics.

2023-01-18 18:11 UTC, ArneGudermann commented
But for now we cann keep this ?

2023-01-18 23:43 UTC, sveneberth reviewed
tbh, I don't see any advantage in this PR. It takes away the possibility to create your completely own rules. Only the existing ones can be activated or deactivated. 
What if I want to force at least 3 special characters?

Apart from the fact that probably nobody changes these rules anyway...

2023-01-19 12:09 UTC, phorward commented
> Apart from the fact that probably nobody changes these rules anyway...

Let's discuss this tomorrow. I'm also not sure, maybe we need some more explanation.

2023-01-20 12:44 UTC, phorward commented
Regex irgendwas

2023-01-24 11:43 UTC, sveneberth requested changes

2023-01-24 11:43 UTC, sveneberth commented on core/bones/password.py
> +    _password_tests: List[Tuple] = [
```suggestion
    password_tests: List[Tuple] = [
```

2023-01-24 11:43 UTC, sveneberth commented on core/bones/password.py
> +        self.password_tests = self._password_tests if password_tests is None else password_tests
```suggestion
        if if password_tests is not None:
            self.password_tests = password_tests
```

2023-01-24 11:43 UTC, sveneberth commented on core/bones/password.py
> +                    smaller this will be invalid.
I'm not a English pro, but i think this sound better.

```suggestion
            :param min_password_length: The minimum length of a password.
                Passwords with a shorter length will be invalid.
```

2023-01-24 11:43 UTC, sveneberth commented on core/bones/password.py
> +            :param password_tests: A list of tuple.The tuple  contains the tests and an error message if the test fails
Low-hanging fruit. Multiple tuple**s**, each has **one** test and text. Additionally it's more a reason/hint than an error message.

```suggestion
            :param password_tests: A list of tuples. The tuple contains the test and a reason for the user if the test fails.
```

2023-01-24 11:43 UTC, sveneberth commented on core/bones/password.py
> +                tests_errors.append(str(test[1]))  # we may need to convert a "translate" object
T think tuple unpacking is more readable and pythonic.

```suggestion
        for test, hint in self.password_tests:
            if re.search(test, value):
                tests_passed += 1
            else:
                tests_errors.append(str(hint))  # we may need to convert a "translate" object
```

2023-01-24 11:43 UTC, sveneberth commented on core/bones/password.py
> +            if re.search(test[0], value):
I would rather use `re.match` than `re.search`. This allows more specific syntax. (e.g. must start with an number and end with a letter).

```suggestion
            if re.match(test[0], value):
```

2023-01-24 11:43 UTC, sveneberth commented on core/bones/password.py
> +        (r"(?=.*\W)", translate("core.bones.password.no_special_characters",
Related to the `re.search` --> `re.match` change, the REs should be:

```suggestion
        (r"^(?=.*[A-Z].*)$", translate("core.bones.password.no_capital_letters",
                                   defaultText="The password entered has no capital letters.")),
        (r"^(?=.*[a-z].*)$", translate("core.bones.password.no_lowercase_letters",
                                   defaultText="The password entered has no lowercase letters.")),
        (r"^(?=.*\d.*)$", translate("core.bones.password.no_digits",
                                defaultText="The password entered has no digits.")),
        (r"^(?=.*\W.*)$", translate("core.bones.password.no_special_characters",
```

Do we need the non-capturing-groups?

---

Furthermore I think it's more efficient to use a compiled version of the REs (`re.compile()`). We can use them several times, but compile them only once.
But I'm unsure how to store these.
If we store them directly in `self.password_tests`, the renderer must create a new list (`[test.pattern, hint for test, hint in self.passsword_tests`), which isn't efficient too.
Maybe we could internal a second list with the compiled versions.

2023-01-24 12:11 UTC, sveneberth commented on core/bones/password.py
> +        self.password_tests = password_tests
@ArneGudermann Sorry for the `if if` in my suggestion. But now you would apply also `password_tests` if they are `None`.

2023-02-03 14:34 UTC, sveneberth submitted a review, later dismissed

2023-02-03 15:43 UTC, phorward commented
I think we should wait with this until #637 is merged, to resolve conflicts first and have the bone structure rendering on the right position.

2023-02-22 22:47 UTC, sveneberth commented
@ArneGudermann Can you resolve the conflict?

2023-02-23 06:27 UTC, ArneGudermann commented
@phorward  and @sveneberth  should be ok now.

2023-03-01 23:02 UTC, phorward requested changes
Hello @ArneGudermann,

Still, I'm having the following notes to discuss about:

1. What do you think of checking the minimum password length using a regex as well? Please take a look into my suggestions. Indeed, this would allow for shorter passwords when other thresholds are met, maybe a test can be marked to be *mandatory* with an additional item to the tuple?
2. The variables `tooShortMessage` and `tooWeakMessage` are over. They should be removed.
3. The pull requests title doesn't match its content: "provide these to the client" is not part of the current code anymore, as the `structure` function is missing. But this might also be a security issue, because attackers can see the password guidelines and can bypass them in case the provided regex does contain a bug.

2023-03-07 14:31 UTC, sveneberth requested changes

2023-03-07 14:31 UTC, sveneberth commented on core/bones/password.py
> +        super().__init__()
```suggestion
        super().__init__(**kwargs)
```

2023-03-07 16:19 UTC, phorward requested changes
Please fix the init super call and consider renaming `password_tests` into just `tests`, as we are in the context of the PasswordBone.

2023-03-07 16:19 UTC, phorward commented on core/bones/password.py
> +        super().__init__()
yes, this is important!!!

2023-03-07 16:19 UTC, phorward commented on core/bones/password.py
> +        return super().structure() | {"password_tests": self.password_tests}
Can we call it justs `tests`? In all occurrences?

2023-03-07 17:33 UTC, phorward approved these changes
I'm fine with this!

2023-03-07 17:36 UTC, sveneberth approved these changes

2023-03-08 12:19 UTC, merged

2023-03-08 12:22 UTC, sveneberth commented
:clap: