Add current module
viur-framework/viur-core pull request #635
Opened 2023-01-30 09:00 UTC by ArneGudermann

This PR replace `utils.current.` and `utils.getCurrentUser()` with a current module.
Related to #632 and #633

2023-01-30 23:19 UTC, phorward commented
@ArneGudermann can you please fix the conflicts that came in with the latest pull request merges first? After that I can start a review.

2023-02-01 21:48 UTC, phorward requested changes
Hello @ArneGudermann, I've found one invalid place (`Request` written in upper-case-order) which must be fixed.

Furthermore, I would like to propose to use the walrus-operator more often in situations like
```python
        user = current.user.get()
        if user:
            ...
```
and
```python
        user = current.user.get()
        if not user:
            ...
```
and use the modern syntax, which is
```python
        if user := current.user.get()
            ...
```
and
```python
        if not (user := current.user.get()):
            ...
```

Can you please apply this?

2023-02-01 21:49 UTC, phorward commented on core/prototypes/singleton.py
>          if not user:
please replace all occurrences like this in the entire PR (there are plenty of them)

2023-02-03 11:53 UTC, sveneberth requested changes
I think the `user` must be set after each login and logout too.

2023-02-03 11:54 UTC, phorward commented
> I think the `user` must be set after each login and logout too.

Haha, exactly this was my thought when I reviewed it right now ;-D

2023-02-20 23:44 UTC, phorward requested changes
@ArneGudermann please check my suggestions from #652 to integrate them here.

2023-02-21 20:08 UTC, phorward commented
@ArneGudermann I've accidentally merged #652 into this branch some minutes ago. I hope you're fine with it and all reviewers comply with the changes. If not, please annotate here.

2023-02-21 20:10 UTC, phorward submitted a review, later dismissed

2023-02-22 06:36 UTC, ArneGudermann commented
@phorward It looks okay for me.

2023-02-22 13:21 UTC, phorward commented
> I think the `user` must be set after each login and logout too.

Dear Mr. @sveneberth can you please re-approve this PR?
The context-variable is set in Request and on the user-module appropriately now.

2023-02-22 13:45 UTC, phorward approved these changes

2023-02-22 15:28 UTC, sveneberth approved these changes
awesome!

2023-02-22 16:29 UTC, merged