Move render structure to the bones
viur-framework/viur-core pull request #637
Opened 2023-01-30 13:18 UTC by ArneGudermann

This PR move the `renderBoneStructure` form the renderer to the  bones to eliminate multiple code. It also move `renderSkelStructure` in the `skeleton`. 
At this stage we still need to include the `render_type` to distinguish which renderer we are in.

2023-01-30 23:20 UTC, phorward commented
@ArneGudermann can you please fix the conflicts that came in with the latest pull request merges first? After that I can start a review.

2023-02-01 22:05 UTC, phorward requested changes
Hello @ArneGudermann,
thanks for providing this pull request. 

Please check my suggestions, there is one error. 

Moreover, please entirely remove the flag `render_type`. Render-specific stuff should not be part of the bones!

I think, it's okay to make `readonly` the only valid key for all renders in ViUR-core 3.4. It is a breaking change and we should explicitly note on this, but one upper case "O" is not a reason to loop-through this parameter for only one case.

Furthermore, we should maybe think to generally write all keys in lower-case order. These changes are breaking, so a viur-core 3.4 must use a speciifc viur-vi 3.1 or similar, which is compatible.

2023-02-01 22:05 UTC, phorward commented on core/bones/base.py
> +            "emptyValue": self.getEmptyValue(),  # fixme: rename this into "emptyvalue", same as "defaultvalue"
```suggestion
            "emptyvalue": self.getEmptyValue(),  # fixme: rename this into "emptyvalue", same as "defaultvalue"
```

2023-02-01 22:05 UTC, phorward commented on core/bones/base.py
> +                "preventDuplicates": self.multiple.preventDuplicates,
```suggestion
                "minamount": self.multiple.minAmount,
                "maxamount": self.multiple.maxAmount,
                "preventduplicates": self.multiple.preventDuplicates,
```

2023-02-01 22:05 UTC, phorward commented on core/bones/base.py
> +                "preventDuplicates": self.multiple.preventDuplicates,
We can do this, because they aren't evaluated somewhere, yet. (Not in the Vi!)

2023-02-01 22:05 UTC, phorward commented on core/bones/spatial.py
> +            "boundsLng": self.boundsLng,
```suggestion
            "boundslat": self.boundsLat,
            "boundslng": self.boundsLng,
```

2023-02-01 22:05 UTC, phorward commented on core/bones/string.py
> +            "maxLength": self.maxLength
```suggestion
            "maxlength": self.maxLength
```

2023-02-02 09:36 UTC, phorward requested changes
This is much better. Can you please fix the suggestions?

2023-02-02 09:36 UTC, phorward commented on core/bones/base.py
> +            "emptyvalue": self.getEmptyValue(),  # fixme: rename this into "emptyvalue", same as "defaultvalue"
The #fixme is now obsolete!
```suggestion
            "emptyvalue": self.getEmptyValue(),
```

2023-02-02 09:36 UTC, phorward commented on core/bones/date.py
> +    def structure(self, ) -> dict:
```suggestion
    def structure(self) -> dict:
```

2023-02-02 09:36 UTC, phorward commented on core/bones/file.py
> +    def structure(self, ) -> dict:
```suggestion
    def structure(self) -> dict:
```

2023-02-02 09:36 UTC, phorward commented on core/bones/record.py
> +    def structure(self, ) -> dict:
```suggestion
    def structure(self) -> dict:
```

2023-02-02 09:36 UTC, phorward commented on core/bones/relational.py
> +    def structure(self, ) -> dict:
```suggestion
    def structure(self) -> dict:
```

2023-02-02 09:36 UTC, phorward commented on core/bones/select.py
> +    def structure(self, ) -> dict:
```suggestion
    def structure(self) -> dict:
```

2023-02-02 09:36 UTC, phorward commented on core/bones/spatial.py
> +    def structure(self, ) -> dict:
```suggestion
    def structure(self) -> dict:
```

2023-02-02 09:36 UTC, phorward commented on core/bones/string.py
> +    def structure(self, ) -> dict:
```suggestion
    def structure(self) -> dict:
```

2023-02-02 09:36 UTC, phorward commented on core/skeleton.py
> +    def structure(self, ):
```suggestion
    def structure(self):
```

2023-02-02 09:38 UTC, phorward commented
I have one more proposal which we should discuss in the viur-meeting: In case we want a full backward compatibility during ViUR3, we can assign several keys twice, like `emptyvalue` and `emptyValue`. Always with a comment for deprecation and removal in ViUR4.

2023-02-02 09:39 UTC, phorward commented on core/bones/base.py
> +                "maxamount": self.multiple.maxAmount,
I'm a fan of short names without redundant information. What do you think? 
```suggestion
                "min": self.multiple.minAmount,
                "max": self.multiple.maxAmount,
```

2023-02-03 14:25 UTC, sveneberth requested changes

2023-02-03 14:25 UTC, sveneberth commented on core/bones/file.py
> +            "validMimeTypes": self.validMimeTypes
This is still camelCase?

Maybe replace by
```suggestion
            "valid_mime_types": self.validMimeTypes
```
or 

```suggestion
            "validmimetypes": self.validMimeTypes
```
?

2023-02-03 14:25 UTC, sveneberth commented on core/bones/text.py
> +            "validHtml": self.validHtml,
keep it camelCase?

2023-02-03 15:22 UTC, phorward commented on core/bones/text.py
> +            "validHtml": self.validHtml,
never!

2023-02-17 10:57 UTC, sveneberth submitted a review, later dismissed

2023-02-17 14:42 UTC, phorward commented on core/skeleton.py
> +        return [(key, bone.structure()) for key, bone in self.items()]
Relates to #649

2023-02-17 14:45 UTC, phorward requested changes
Hello @ArneGudermann, this looks nice already.

I still have one thing I want to change before merging: `skel.structure()` should return a dict. The `[[key, descr]...]`-list notation is a specialty of the JSON-renderer, and should only be generated there.

2023-02-17 15:33 UTC, phorward commented
@ArneGudermann if you approve #651 all my wishes are being respected! :1st_place_medal:

2023-02-17 17:38 UTC, phorward commented
@sveneberth I've merged #651 into this PR to provide two flags to make this PR fully backward-compatible with `viur-core<3.4`, but to allow configure a project to use new features on demand. Can you please review this, so this can be merged, making a release candidate possible?

2023-02-21 19:14 UTC, sveneberth commented
from the code it looks okay, but my Vi crashes:
```
['user', 'list']
15pyodide.asm.js:14 userlist does not exist or is not registered!
pyodide.asm.js:14 Python exception:
Traceback (most recent call last):
  File "/build/flare/flare/network.py", line 125, in onReadyStateChange
  File "/build/flare/flare/network.py", line 519, in onCompletion
  File "/build/widgets/list.py", line 370, in receivedStructure
ValueError: too many values to unpack (expected 2)


log_python_error @ pyodide.asm.js:14
$pythonexc2js @ pyodide.asm.wasm:0xe6fb3
Module._pythonexc2js @ pyodide.asm.js:14
Module.callPyObjectKwargs @ pyproxy.gen.js:405
Module.callPyObject @ pyproxy.gen.js:411
apply @ pyproxy.gen.js:1199
apply @ pyproxy.gen.js:1076
XMLHttpRequest.send (async)
hiwire_call_bound @ pyodide.asm.js:14
$func349 @ pyodide.asm.wasm:0xe87a1
$func3026 @ pyodide.asm.wasm:0x1f41fe
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1f1ed0
$_PyEval_EvalCode @ pyodide.asm.wasm:0x1ed755
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x121b2f
$func1022 @ pyodide.asm.wasm:0x1236bd
$_pyproxy_apply @ pyodide.asm.wasm:0xea93b
Module.callPyObjectKwargs @ pyproxy.gen.js:391
Module.callPyObject @ pyproxy.gen.js:411
apply @ pyproxy.gen.js:1199
apply @ pyproxy.gen.js:1076
hiwire_call_bound @ pyodide.asm.js:14
$func349 @ pyodide.asm.wasm:0xe87a1
$func3026 @ pyodide.asm.wasm:0x1f41fe
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1f1ed0
$_PyEval_EvalCode @ pyodide.asm.wasm:0x1ed755
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x121b2f
$_PyObject_FastCallDictTstate @ pyodide.asm.wasm:0x12142d
$_PyObject_Call_Prepend @ pyodide.asm.wasm:0x121ef6
$func2315 @ pyodide.asm.wasm:0x17f2a2
$func2220 @ pyodide.asm.wasm:0x176e7a
method_call_trampoline @ pyodide.asm.js:14
$_PyObject_MakeTpCall @ pyodide.asm.wasm:0x121318
$func3026 @ pyodide.asm.wasm:0x1f41e1
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1f1f4d
$func979 @ pyodide.asm.wasm:0x121c58
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x121aa0
$func3026 @ pyodide.asm.wasm:0x1f41fe
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1f1ef0
$func979 @ pyodide.asm.wasm:0x121c58
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x121aa0
$func3026 @ pyodide.asm.wasm:0x1f41fe
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1f1ef0
$_PyEval_EvalCode @ pyodide.asm.wasm:0x1ed755
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x121b2f
$_PyObject_FastCallDictTstate @ pyodide.asm.wasm:0x12142d
$_PyObject_Call_Prepend @ pyodide.asm.wasm:0x121ef6
$func2315 @ pyodide.asm.wasm:0x17f2a2
$func2220 @ pyodide.asm.wasm:0x176e7a
method_call_trampoline @ pyodide.asm.js:14
$_PyObject_MakeTpCall @ pyodide.asm.wasm:0x121318
$func3026 @ pyodide.asm.wasm:0x1f41e1
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1f1f4d
$_PyEval_EvalCode @ pyodide.asm.wasm:0x1ed755
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x121b2f
$func3026 @ pyodide.asm.wasm:0x1f41fe
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1f1f91
$func979 @ pyodide.asm.wasm:0x121c58
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x121aa0
$func3026 @ pyodide.asm.wasm:0x1f41fe
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1f1ef0
$_PyEval_EvalCode @ pyodide.asm.wasm:0x1ed755
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x121b2f
$_PyObject_FastCallDictTstate @ pyodide.asm.wasm:0x121463
$_PyObject_Call_Prepend @ pyodide.asm.wasm:0x121ef6
$func2315 @ pyodide.asm.wasm:0x17f2a2
$func2220 @ pyodide.asm.wasm:0x176e7a
$_PyObject_Call @ pyodide.asm.wasm:0x1219c9
$PyObject_Call @ pyodide.asm.wasm:0x121a2d
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1f243a
$func979 @ pyodide.asm.wasm:0x121c58
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x121aa0
$func3026 @ pyodide.asm.wasm:0x1f41fe
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1f1ef0
$_PyEval_EvalCode @ pyodide.asm.wasm:0x1ed755
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x121b2f
$_PyObject_FastCallDictTstate @ pyodide.asm.wasm:0x12142d
$_PyObject_Call_Prepend @ pyodide.asm.wasm:0x121ef6
$func2315 @ pyodide.asm.wasm:0x17f2a2
$func2220 @ pyodide.asm.wasm:0x176e7a
method_call_trampoline @ pyodide.asm.js:14
$_PyObject_MakeTpCall @ pyodide.asm.wasm:0x121318
$func3026 @ pyodide.asm.wasm:0x1f41e1
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1f1f4d
$func979 @ pyodide.asm.wasm:0x121c58
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x121aa0
$func3026 @ pyodide.asm.wasm:0x1f41fe
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1f1ef0
$_PyEval_EvalCode @ pyodide.asm.wasm:0x1ed755
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x121b2f
$func1022 @ pyodide.asm.wasm:0x1237c9
$PyVectorcall_Call @ pyodide.asm.wasm:0x121865
$_PyObject_Call @ pyodide.asm.wasm:0x12195f
$PyObject_Call @ pyodide.asm.wasm:0x121a2d
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1f243a
$_PyEval_EvalCode @ pyodide.asm.wasm:0x1ed755
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x121b2f
$func3026 @ pyodide.asm.wasm:0x1f41fe
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1f1ef0
$_PyEval_EvalCode @ pyodide.asm.wasm:0x1ed755
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x121b2f
$func3026 @ pyodide.asm.wasm:0x1f41fe
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1f1ef0
$func979 @ pyodide.asm.wasm:0x121c58
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x121aa0
$func3026 @ pyodide.asm.wasm:0x1f41fe
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1f1ef0
$_PyEval_EvalCode @ pyodide.asm.wasm:0x1ed755
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x121b2f
$func1022 @ pyodide.asm.wasm:0x1236bd
$func3026 @ pyodide.asm.wasm:0x1f41fe
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1f1f4d
$_PyEval_EvalCode @ pyodide.asm.wasm:0x1ed755
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x121b2f
$_pyproxy_apply @ pyodide.asm.wasm:0xea93b
Module.callPyObjectKwargs @ pyproxy.gen.js:391
Module.callPyObject @ pyproxy.gen.js:411
apply @ pyproxy.gen.js:1199
apply @ pyproxy.gen.js:1076
pyodide.asm.js:14 Uncaught PythonError: Traceback (most recent call last):
  File "/build/flare/flare/network.py", line 125, in onReadyStateChange
  File "/build/flare/flare/network.py", line 519, in onCompletion
  File "/build/widgets/list.py", line 370, in receivedStructure
ValueError: too many values to unpack (expected 2)

    at new_error (pyodide.asm.js:14:247183)
    at pyodide.asm.wasm:0xe6eb0
    at pyodide.asm.wasm:0xe6fae
    at Module._pythonexc2js (pyodide.asm.js:14:944230)
    at Module.callPyObjectKwargs (pyproxy.gen.js:405:12)
    at Module.callPyObject (pyproxy.gen.js:411:17)
    at PyProxyClass.apply (pyproxy.gen.js:1199:19)
    at Object.apply (pyproxy.gen.js:1076:18)
new_error @ pyodide.asm.js:14
$wrap_exception @ pyodide.asm.wasm:0xe6eb0
$pythonexc2js @ pyodide.asm.wasm:0xe6fae
Module._pythonexc2js @ pyodide.asm.js:14
Module.callPyObjectKwargs @ pyproxy.gen.js:405
Module.callPyObject @ pyproxy.gen.js:411
apply @ pyproxy.gen.js:1199
apply @ pyproxy.gen.js:1076
XMLHttpRequest.send (async)
hiwire_call_bound @ pyodide.asm.js:14
$func349 @ pyodide.asm.wasm:0xe87a1
$func3026 @ pyodide.asm.wasm:0x1f41fe
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1f1ed0
$_PyEval_EvalCode @ pyodide.asm.wasm:0x1ed755
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x121b2f
$func1022 @ pyodide.asm.wasm:0x1236bd
$_pyproxy_apply @ pyodide.asm.wasm:0xea93b
Module.callPyObjectKwargs @ pyproxy.gen.js:391
Module.callPyObject @ pyproxy.gen.js:411
apply @ pyproxy.gen.js:1199
apply @ pyproxy.gen.js:1076
hiwire_call_bound @ pyodide.asm.js:14
$func349 @ pyodide.asm.wasm:0xe87a1
$func3026 @ pyodide.asm.wasm:0x1f41fe
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1f1ed0
$_PyEval_EvalCode @ pyodide.asm.wasm:0x1ed755
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x121b2f
$_PyObject_FastCallDictTstate @ pyodide.asm.wasm:0x12142d
$_PyObject_Call_Prepend @ pyodide.asm.wasm:0x121ef6
$func2315 @ pyodide.asm.wasm:0x17f2a2
$func2220 @ pyodide.asm.wasm:0x176e7a
method_call_trampoline @ pyodide.asm.js:14
$_PyObject_MakeTpCall @ pyodide.asm.wasm:0x121318
$func3026 @ pyodide.asm.wasm:0x1f41e1
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1f1f4d
$func979 @ pyodide.asm.wasm:0x121c58
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x121aa0
$func3026 @ pyodide.asm.wasm:0x1 [...]

2023-02-21 20:01 UTC, phorward commented
> So it looks like the compatibility isn't working...

Damn! You're right and I've fixed it also for the vi in [4c59569](https://github.com/viur-framework/viur-core/pull/637/commits/4c59569181098b413d0531059d29e8dccbb6ac06). Please retry.

2023-02-21 20:03 UTC, phorward approved these changes

2023-02-21 23:35 UTC, sveneberth approved these changes

2023-02-22 11:12 UTC, merged