Add Conf var for dev_server_cloud_logging
viur-framework/viur-core pull request #638
Opened 2023-01-31 16:21 UTC by ArneGudermann

With this PR you can now set if you want to see your local log entries also in google cloud logger. I don't think it's necessary to send all your logs to google, because it costs time and memory unnecessarily. 
It also halves the response time in the local mode for simple requests.

2023-02-01 06:14 UTC, XeoN-GHMB submitted a review, later dismissed

2023-02-01 21:42 UTC, phorward approved these changes

2023-02-02 09:22 UTC, phorward requested changes

2023-02-02 09:22 UTC, phorward commented on core/config.py
> +    "viur.dev_server_cloud_logging": True,
```suggestion
    "viur.dev_server_cloud_logging": False,
```
shouldn't this be False by default?

2023-02-03 11:33 UTC, sveneberth approved these changes

2023-02-03 15:20 UTC, phorward approved these changes

2023-02-03 15:21 UTC, merged