Added tzNaive flag to dateBone
viur-framework/viur-core pull request #642
Opened 2023-02-03 18:52 UTC by AchimSchumacher

This is in order to ensure a DateBone is rendered independently of any local time zone.
As in viur3 all DateBones are timezone aware, per default set to UTC. When rendered into JSON, values are Strings in isoformat, i.e. "YYYY-MM-DDTHH:MM:SS+HH:MM". In UTC, this is always "YYYY-MM-DDTHH:MM:SS+00:00".
In JS, e.g. vuejs, in order to obtain a String representation in local format, "new Date(value).toLocaleString(window.navigator.language)" not only changes language but also converts into local time.
This may be undesired, e.g. a workdate confirmed with a client should not change time the moment summertime starts. When talking to the client, both parties should see the same time, even if living in different timezones.

The implementation chosen only adds the flag to DateBone w/o any further changes. In the default JSON renderer, the flag is   then read and results simply in the "+00:00" part being removed from the String. This is enough for local Date objects initialized from the String to be timezone naive. If needed, other renderers should be updated, too.

Defining tzNaive=True in the Skeleton has the advantage of defining this behavior globally for all clients rather hacking it into each client individually. 

The alternative approach of using a tz-naive Date-object internally in DateBone would implicitly convert to local tz w/o control, e.g. in datetime.fromtimestamp(). Furthermore, such a substantial change would be error prone.

2023-02-17 11:57 UTC, sveneberth reviewed
The finally rendering of the datetime is not the task of the core, it's the part of the frontend.
If you don't need localization use an unlocalized `DateBone` (`DateBone(localize=False)`, which is the default anyway). 
And display in your `Vue.Js` always the Date in UTC:
```js
new Date(date_from_skel).toLocaleString('default', {timeZone: 'UTC'})
```

2023-02-17 14:25 UTC, AchimSchumacher commented
> The finally rendering of the datetime is not the task of the core, it's the part of the frontend. 
And yet render/json/default.py is part of core, so I added the change there.

> If you don't need localization use an unlocalized `DateBone` (`DateBone(localize=False)`, which is the default anyway). 
That's not the point. localize=True would tell DateBone to guess the user's time zone, while localize=False uses UTC. In both cases, DateBone uses localized (as in time-zone aware) Dates.

> And display in your `Vue.Js` always the Date in UTC:
> 
> ```js
> new Date(date_from_skel).toLocaleString('default', {timeZone: 'UTC'})
> ```
Yes, one could tell Date.toLocaleString the time zone we are interested in. But then, at the time of rendering, one has to know which DateBone has to be rendered in local time and which one in UTC time.

All the PR does is adding a flag so that at the time of defining the DateBone in a Skeleton, one can set this behavior, i.e. where we can prevent the clients from  transforming the Date into some supposed local time zone.

2023-02-22 22:15 UTC, sveneberth commented
> Yes, one could tell Date.toLocaleString the time zone we are interested in. But then, at the time of rendering, one has to know which DateBone has to be rendered in local time and which one in UTC time.

You could add a flag in your bone params if this particular type of rendering is required.


However, the main problem with this implementation is that it is inconsistent across all renderers and the skeleton.
The renderers should output an appropriate representation for the data stored in the skeleton without corrupting the data or truncating data.

2023-02-28 11:43 UTC, AchimSchumacher commented
> However, the main problem with this implementation is that it is inconsistent across all renderers and the skeleton. 

It is inconsistent across all renderers as long as it is implemented only in the json renderer. You are correct in that the same behavior should be implemented in all other renderers, too.

> The renderers should output an appropriate representation for the data stored in the skeleton without corrupting the data or truncating data.

This is the point of the PR. Without it, renderers do not output an appropriate representation for the data stored in the skeleton, for the case of a Date which should not underly any changes due to time zone or daylight saving time. As is, these Dates are corrupted by applying a time-shift which does not correspond to the Date. 

The data isn't truncated, neither, although obviously a part of the string is truncated. That truncated part is exactly telling the receiver the Date is timezone-aware, which actually is corrupting the data.

2023-03-01 22:22 UTC, phorward requested changes
Hello @AchimSchumacher,
thanks for filing this pull request.

First of all, please
1. Fix the merge conflicts with the current develop branch
2. Don't use `tzNaive` as flag name; use `naive` or another name which does not use camel-case.
3. Your code bypasses current rendering of `datetime` values, which is done in the CustomJsonEncoder. This code will be replaced soon by a more generic value rendering (likewise #637). It is ok for me, but we should discuss it.

2023-03-01 22:22 UTC, phorward commented on core/bones/date.py
> +        tzNaive: bool = False,
Please change this for PEP8-compliance, into something like
```suggestion
        naive: bool = False,
```

2023-03-03 12:36 UTC, phorward commented
@sveneberth will provide an alternative attempt.

2023-04-01 07:22 UTC, phorward commented
This pull request is replaced by #667 and will be closed now.

2023-04-01 07:22 UTC, closed without merging