Implement naive mode in `DateBone`
viur-framework/viur-core pull request #667
Opened 2023-03-06 16:44 UTC by sveneberth

Because the datastore (currently) enforces datetime aware objects we need to remove/add the tzinfo on (un)serialize.

This is a replacement for #642

2023-04-01 07:20 UTC, phorward approved these changes

2023-04-01 07:20 UTC, phorward commented
I'm fine with this solution.
@AchimSchumacher can you please re-review on this and add your approval?

2023-04-03 19:54 UTC, AchimSchumacher requested changes

2023-04-03 19:54 UTC, AchimSchumacher commented on core/bones/date.py
> +                if self.naive:
Same error here: It must be 'if not self.naive:'

2023-04-04 14:52 UTC, phorward approved these changes

2023-04-11 14:14 UTC, phorward approved these changes

2023-04-12 08:46 UTC, merged