feat: Provide `firstname` and `lastname` to UserSkel
viur-framework/viur-core pull request #677
Opened 2023-03-08 12:13 UTC by phorward

This should become standard to allow for better pre-defined personalization.

2023-03-08 13:32 UTC, sveneberth commented
Okay for me, but fill a new skel with the information from the google login
https://github.com/viur-framework/viur-core/blob/209396bf72a1fea6fdffac13c825397b50728b71/core/modules/user.py#L448

2023-03-08 21:32 UTC, sveneberth requested changes
Please fill them with values, as in https://github.com/viur-framework/viur-core/pull/677

2023-03-09 10:58 UTC, phorward commented
> Please fill them with values, as in #677

you mean #2?!

2023-03-09 11:20 UTC, phorward commented
@sveneberth I've added a `synced`-Flag to let the user decide if information should be kept synchronous with Google.
I've also changed the way how the `update`-flag is being determined.

2023-03-09 20:32 UTC, sveneberth requested changes

2023-03-09 20:32 UTC, sveneberth commented on core/modules/user.py
> +    synced = BooleanBone(
```suggestion
    sync = BooleanBone(
```
Please rename this bone to `sync`.

2023-03-09 20:32 UTC, sveneberth commented on core/modules/user.py
> +            logging.debug(f"""{userSkel["synced"]=}""")
```suggestion
        if userSkel["sync"]:
```

2023-03-09 20:32 UTC, sveneberth commented on core/modules/user.py
> +                logging.debug(f"""{target=} {source=}""")
```suggestion
```

2023-03-09 20:32 UTC, sveneberth commented on core/modules/user.py
> +        logging.debug(f"{update=}")
```suggestion
```

2023-03-26 18:08 UTC, sveneberth approved these changes

2023-03-26 19:58 UTC, merged