feat: Improvements on `securitykey.validate`
viur-framework/viur-core pull request #704
Opened 2023-04-11 19:40 UTC by phorward

- `useSessionKey=True` is now default
- `pre_condition`-parameter to auto-raise a PreconditionFailed() exception
- Replaced and optimized calls in viur-core
- 100% backwards compatible to existing calls

I don't know why `useSessionKey=True` was always explicitly provided, as you can see below:
![before](https://user-images.githubusercontent.com/16870072/231270840-1214317e-46e2-4594-addd-9b142ffc8891.jpg)

2023-04-11 19:40 UTC, phorward commented
This can be seen as an improvement on #656

2023-04-14 10:47 UTC, sveneberth requested changes

2023-04-14 10:47 UTC, sveneberth commented on core/modules/file.py
>              skey = kwargs.get("skey")
If `kwargs` doesn't contains the `skey` it's `None`. But the type hint enforces a `str` (`def validate(key: str, ...)`).

Therefore I suggest this change:

```suggestion
            skey = kwargs.get("skey", "")
```

2023-04-14 10:48 UTC, sveneberth commented
Let's talk about a decorator. I use this in ViUR2:

```
def skeyRequired(func=None, **decoratorKwArgs):
	"""Decorator that checks the skey before the method is called.

	Optional callable to pass keyword-arguments for the securitykey.validate-call.

	Example:
		>>> from server import exposed
		>>> @exposed
		>>> @skeyRequired
		>>> def yourMethod(self):
		>>>     return {"foo": "bar"}
	"""

	def outerWrapper(f):
		@functools.wraps(f)
		def wrapper(*args, **kwargs):
			if not securitykey.validate(kwargs.pop("skey", ""), **decoratorKwArgs):
				raise errors.PreconditionFailed("Missing or invalid skey")
			return f(*args, **kwargs)

		return wrapper

	if isinstance(func, (types.MethodType, types.FunctionType)):
		return outerWrapper(func)  # @skeyRequired
	else:
		return outerWrapper  # @skeyRequired() or @skeyRequired(**anyKwargs)
```

2023-04-14 13:56 UTC, phorward commented
In today's viur-meeting, we decided to solve it by a decorator. I'm with you, but anyway would like to merge this PR as is and integrate the feature set into the code-base.

2023-06-13 11:59 UTC, phorward commented
Closed as superseded by #764

2023-06-13 11:59 UTC, closed without merging