feat: Delete old pending `FileSkeletons`
viur-framework/viur-core pull request #739
Opened 2023-05-05 16:31 UTC by sveneberth

Over time, pending FileSkeletons (datastore entities) can accumulate when upload urls have been requested but nothing has been uploaded. Therefore this adds the PeriodicTask `start_delete_pending_files` which deletes pending files older than 90 days.

To do the deletion safely on skeleton level a customization of the `DeleteEntitiesIter` was necessary. I see no reason not to use this for skeletons as long as you call the appropriate `.delete()` method.

2023-05-05 16:38 UTC, ArneGudermann commented
Why 90 day a Uploadurl is expired after 1 hour (https://github.com/viur-framework/viur-core/blob/a54556277b9e719b50863a2d20771ed8375058de/core/modules/file.py#L467)  .
Can we say 1 day or so ?

2023-05-05 17:15 UTC, sveneberth commented
> Why 90 day a Uploadurl is expired after 1 hour

But only for signed URLs from this method (`signUploadURL`), which isn't used anywhere in the core.
URLs created by `getUploadURL` seems to be unlimited?!

Tbh, the 90 doesn't have a specific reason. It should be a time that is enough to process an upload, but not unlimited.
I can't imagine a case where you need a validity of several days. For user uploads, you would actually always pick up the URL immediately before the upload.
So for me, 1 day would also be okay. What do the others (/ping @viur-framework/developers and especially @phorward) think?

2023-05-12 11:30 UTC, phorward commented
In the viur meeting, we decided to set this value to 7 days.

2023-05-12 14:23 UTC, sveneberth commented on core/modules/file.py
> +    Start deletion of pending FileSkels that are older than 90 days.
```suggestion
    Start deletion of pending FileSkels that are older than 7 days.
```

2023-05-15 18:53 UTC, phorward requested changes
Hello @sveneberth, looks OK to me, can you review the two comments?

2023-05-15 18:53 UTC, phorward commented on core/modules/file.py
> +        .filter("creationdate <", datetime.now() - timedelta(days=7))
I'm not sure, but shall be use `utcNow()` here, as `creationdate` is a timezone-aware value?
```suggestion
        .filter("creationdate <", utils.utcNow() - timedelta(days=7))
```

2023-05-15 18:53 UTC, phorward commented on core/tasks.py
> +                        logging.error("Exiting queryIter on cursor %s" % qry.getCursor())
Please use f-strings!
```suggestion
                        logging.error(f"Exiting queryIter on cursor {qry.getCursor()!r}")
```

2023-06-07 10:09 UTC, phorward approved these changes

2023-06-07 11:31 UTC, merged