docs: fixed alll Autoapi build Errors
viur-framework/viur-core pull request #783
Opened 2023-07-11 15:06 UTC by Grashalmbeisser

I took some time to fix all Errors that happen while the Autoapi builds the Documentation

2023-07-12 09:53 UTC, sveneberth requested changes
Hey @Grashalmbeisser, Please make sure that all pipelines have been passed through successfully. There are several PEP8 errors.

2023-07-18 10:10 UTC, phorward commented on core/bones/file.py
> +                 validMimeTypes: Union[None, List[str]] = None, **kwargs):
Can you please keep the previous notation? Splitting the signature over multiple lines makes the code more maintainable and readable.

2023-07-18 13:39 UTC, phorward approved these changes

2023-07-18 13:40 UTC, phorward commented
> Hey @Grashalmbeisser, Please make sure that all pipelines have been passed through successfully. There are several PEP8 errors.

Meanwhile, this was fixed. Please re-review and approve.

2023-07-21 14:02 UTC, phorward approved these changes

2023-07-21 14:02 UTC, merged