feat: Add bones parameter for renderEditForm
viur-framework/viur-core pull request #812
Opened 2023-08-15 07:06 UTC by ArneGudermann

This PR extends the function `renderEditForm` with the parameter `bones`. If this is set, only the bones that are in the list will be rendered.

2023-08-15 14:40 UTC, sveneberth requested changes

2023-08-15 14:40 UTC, sveneberth commented on src/viur/core/render/html/env/viur.py
> +
Can we add a check like this before?

```suggestion

if both := set(ignore).intersection(bones):
    raise ValueError(f"You have specified the same bones {', '.join(both)} in *ignore* AND *bones*!")
```

2023-08-15 15:49 UTC, sveneberth commented on src/viur/core/render/html/env/viur.py
> +    raise ValueError(f"You have specified the same bones {', '.join(both)} in *ignore* AND *bones*!")
```suggestion
    if both := set(ignore).intersection(bones):
        raise ValueError(f"You have specified the same bones {', '.join(both)} in *ignore* AND *bones*!")
```

2023-08-15 15:50 UTC, sveneberth approved these changes

2023-08-18 15:50 UTC, phorward approved these changes

2023-08-18 15:50 UTC, merged