refactor: Prototype action functions
viur-framework/viur-core pull request #831
Opened 2023-09-06 16:26 UTC by phorward

This pull requests refactors the code for all prototype standard actions as follows:

- Consequent use of "key" in signature
- Clean-up kwargs check
- Clean-up "bounce" check
- Make code more readable
- Instanciate variables right before their use, and not on top

2023-09-06 17:05 UTC, sveneberth submitted a review, later dismissed
LGTM, but I've some related suggestions: https://github.com/phorward/viur-core/pull/5

2023-09-07 06:01 UTC, ArneGudermann requested changes

2023-09-07 06:01 UTC, ArneGudermann commented on src/viur/core/prototypes/list.py
> +    def view(self, key: db.Key | str | int, *args, **kwargs) -> Any:
This is stands for all (`edit`,...)

2023-09-07 10:26 UTC, phorward commented
> LGTM, but I've some related suggestions: [phorward#5](https://github.com/phorward/viur-core/pull/5)

Can we please do this PR separately after merge?

2023-09-07 11:27 UTC, ArneGudermann commented
Can you take a look at https://github.com/phorward/viur-core/pull/6. Than I'm fine with this.

2023-09-07 12:21 UTC, phorward commented
> Can you take a look at [phorward#6](https://github.com/phorward/viur-core/pull/6). Than I'm fine with this.

No, because this ["kinda hackish" thing](https://github.com/viur-framework/viur-core/blob/main/core/request.py#L642) is the reason why no 406, but 500 is thrown.  Therefore, I won't merge it, and would like to merge this PR as a step towards a more stable version.

2023-09-07 12:21 UTC, phorward commented on src/viur/core/prototypes/list.py
> +    def view(self, key: db.Key | str | int | None = None, *args, **kwargs) -> Any:
Turn this back.
```suggestion
    def view(self, key: db.Key | str | int | None, *args, **kwargs) -> Any:
```

2023-09-07 19:25 UTC, merged