Implement the Config as (real) Object with attributes
viur-framework/viur-core pull request #833
Opened 2023-09-06 21:36 UTC by sveneberth

This allows to group option and the IDE can autocomplete the names. This implementation is (hopefully) 100 % backwards compatible.

---

I publish this as draft, because I need to test a bit more, add documentation, remove debugs and so on.
I think we could also structure some things even better now. For example, I don't think much of this viur prefix.
I can also show this in detail in the next viur meeting.

But feel free to share your opinions and give feedback.

2023-10-06 10:21 UTC, phorward commented
@sveneberth can you please resolve the conflicts with current develop? I would like to review this feature soon.

2023-10-23 04:16 UTC, XeoN-GHMB approved these changes

2023-10-25 12:27 UTC, phorward requested changes
Hello @sveneberth, thanks for making this huge change.
I've found some replacements which break the OTP-second-factor-stuff, maybe its came in by automatic replacement, can you please re-check this?

2023-10-25 13:17 UTC, sveneberth commented on src/viur/core/config.py
> +            key = key[len("viur."):]
I'm going to test this, but could be enough. I'm going to test this, but could be enough. If things successively arise and at some point you can no longer see the forest for the trees …

2023-10-25 19:46 UTC, phorward requested changes
Hello @sveneberth, I found one more invalid place in the code, please fix this!

2023-10-25 19:46 UTC, phorward commented on src/viur/core/modules/user.py
> +        timedriftchange = float(res) - otp_user_conf.timedrift
This is still broken!
```suggestion
        timedriftchange = float(res) - otp_user_conf["timedrift"]
```

2023-10-25 20:00 UTC, phorward approved these changes

2023-10-27 09:32 UTC, ArneGudermann approved these changes

2023-10-27 14:31 UTC, merged

2023-10-27 15:02 UTC, sveneberth commented
🎉