Fix: maxLength chekc in Stringbone
viur-framework/viur-core pull request #941
Opened 2023-11-21 17:58 UTC by ArneGudermann

This PR fixes the problem that the value was always shortened to the maximum length before it was checked for the maximum length and so you simply lose data without getting an error message

2023-11-21 18:28 UTC, sveneberth reviewed
I see your intention, but both solution have their right for existence.

Imagine you want to send data to an external API that has a length limit. You set your bone to this limit to ensure that it will not exceed it. But then the user enters a word with the maximum length and umlauts. To prevent the API from rejecting this value, you have to guess a suitable lower limit for your bone, unquote the value (btw. why do we quote values for the database, it might be time to restart this discussion :see_no_evil:) or slice it.

2023-11-21 20:48 UTC, phorward commented
Let's discuss this on friday.

2023-11-22 12:41 UTC, phorward commented
I would like to first merge #942, then #940  and afterwards update this PR for discussion on friday. Is that ok?

2023-11-24 12:36 UTC, phorward requested changes

2023-11-24 12:36 UTC, phorward commented on src/viur/core/bones/string.py
> +            return utils.escapeString(value, self.maxLength), None
```suggestion
            return utils.escapeString(value, None), None
```

2023-11-24 17:09 UTC, sveneberth approved these changes

2023-12-04 11:15 UTC, merged