Refactor: Rename maxLength with max_length.
viur-framework/viur-core pull request #942
Opened 2023-11-21 18:32 UTC by ArneGudermann

Replace all `maxLength` with `max_length` and a backwards compatible check with a warning.

2023-11-21 18:55 UTC, sveneberth requested changes

2023-11-21 18:55 UTC, sveneberth commented on src/viur/core/render/json/default.py
> +                    "max_length": "max_length",
```suggestion
                    "maxlength": "max_length",
```

2023-11-21 18:55 UTC, sveneberth commented on src/viur/core/utils.py
> +        warnings.warn("maxLength is deprecated, please use max_length")
Sorry, my suggestion in the other PR wasn't complete, please add the class:
```suggestion
        warnings.warn("maxLength parameter is deprecated, please use max_length", DeprecationWarning)
```

2023-11-21 18:55 UTC, sveneberth commented on src/viur/core/bones/text.py
> +            warnings.warn("maxLength is deprecated, please use max_length")
Sorry, my suggestion in the other PR wasn't complete, please add the class:
```suggestion
            warnings.warn("maxLength parameter is deprecated, please use max_length", DeprecationWarning)
```

2023-11-21 18:55 UTC, sveneberth commented on src/viur/core/bones/string.py
> +            "max_length": self.max_length
```suggestion
            "maxlength": self.max_length
```

2023-11-21 18:55 UTC, sveneberth commented on src/viur/core/bones/string.py
> +            warnings.warn("maxLength is deprecated, please use max_length")
```suggestion
            warnings.warn("maxLength parameter is deprecated, please use max_length", DeprecationWarning)
```

2023-11-22 12:40 UTC, phorward requested changes
Hello @ArneGudermann, thanks for enforcing this, can you please correct the two suggestions?

2023-11-22 12:40 UTC, phorward commented on src/viur/core/render/json/default.py
> +                    "maxlength": "max_length",
This is invalid, as this is the compatibility for the old bone structure rendering, and there, "maxLength" is the old value required.
```suggestion
                    "maxlength": "maxLength",
```

2023-11-22 12:40 UTC, phorward commented on src/viur/core/utils.py
> +        return val[0:max_length]
```suggestion
        return val[:max_length]
```

2023-11-22 13:14 UTC, phorward commented
@ArneGudermann can you please also resolve the conflicts which came in by #940 ?

2023-11-22 13:49 UTC, sveneberth approved these changes

2023-11-22 13:51 UTC, sveneberth requested changes

2023-11-22 13:53 UTC, sveneberth requested changes

2023-11-22 13:53 UTC, sveneberth commented on src/viur/core/bones/string.py
> +
```suggestion
```

2023-11-22 18:16 UTC, sveneberth approved these changes

2023-11-23 00:52 UTC, phorward approved these changes

2023-11-23 00:53 UTC, merged