refactor value for `tasks_custom_environment_handler` to new abstract class `CustomEnvironmentHandler`
viur-framework/viur-core pull request #946
Opened 2023-11-26 23:45 UTC by sveneberth

tuples are still accepted for backward compatibility

Resolves #920

2024-01-14 09:38 UTC, phorward requested changes

2024-01-14 09:38 UTC, phorward commented on src/viur/core/config.py
> +            klass = type("ProjectCustomEnvironmentHandler", (CustomEnvironmentHandler,),
@sveneberth this is my only point, afterwards we can merge.

2024-01-15 13:02 UTC, sveneberth commented on src/viur/core/config.py
> +            klass = type("ProjectCustomEnvironmentHandler", (CustomEnvironmentHandler,),
okay, done

2024-02-01 11:33 UTC, phorward approved these changes

2024-02-01 11:33 UTC, merged