Fix: compute for relational bones
viur-framework/viur-core pull request #950
Opened 2023-11-28 17:41 UTC by ArneGudermann

Fix for: #943

2024-01-10 21:45 UTC, sveneberth requested changes

2024-01-10 21:45 UTC, sveneberth commented on src/viur/core/bones/base.py
> +            if skel.skel_type == "RefSkel":  # we have a ref skel we must load the complete skeleton
I think the attribute `skel_type` is not necessary:

```suggestion
            if issubclass(skel.skeletonCls, RefSkel):  # we have a ref skel we must load the complete skeleton
```

2024-01-10 21:45 UTC, sveneberth commented on src/viur/core/bones/base.py
> +                cloned_skel[bone_name] = None  # remove value form accessedValues to avoid endless recursion
```suggestion
            cloned_skel[bone_name] = None  # remove value form accessedValues to avoid endless recursion
```

2024-01-10 21:45 UTC, sveneberth commented on src/viur/core/bones/base.py
> +                cloned_skel[bone_name] = None  # remove value form accessedValues to avoid endless recursion
```suggestion
```

2024-01-12 15:10 UTC, sveneberth commented on src/viur/core/skeleton.py
> +    skel_type = "BaseSkeleton"
```suggestion
```

2024-01-26 10:28 UTC, sveneberth commented
Hey there, can we get this PR in a final review-able state. I think would be good first solution, until we have a some more efficient.

2024-01-30 11:53 UTC, phorward approved these changes

2024-01-30 11:53 UTC, merged