reactor: `fromDB` method.
viur-framework/viur-core pull request #968
Opened 2023-12-06 15:42 UTC by ArneGudermann

2023-12-06 23:52 UTC, sveneberth requested changes
https://github.com/viur-framework/viur-core/pull/968/files#r1418128317

2024-01-14 09:40 UTC, phorward commented
@ArneGudermann can you please verify the correctness of @sveneberth's comment, and resolve conflicts?

2024-01-17 22:49 UTC, phorward approved these changes

2024-01-17 22:49 UTC, phorward commented on src/viur/core/skeleton.py
> -        skelValues["key"] = dbKey
That is correct, as the `KeyBone` has a special handling when bone is called `key`.

2024-01-18 12:13 UTC, phorward approved these changes

2024-01-19 15:26 UTC, merged