refactor:`Skeleton.toDB` method
viur-framework/viur-core pull request #973
Opened 2023-12-07 09:27 UTC by ArneGudermann

2024-01-17 22:44 UTC, phorward approved these changes
Hello @ArneGudermann, let's check it out.
Some parts of this PR will conflict with #1025

2024-01-17 22:44 UTC, phorward commented on src/viur/core/skeleton.py
> +                                raise ValueError(f"The unique value '{skel[bone_name]}' of bone '{bone_name}' has been recently claimed!")
```suggestion
                                raise ValueError(
                                    f"The unique value '{skel[bone_name]}' of bone '{bone_name}' "
                                    "has been recently claimed!"
                                )
```

2024-01-17 22:46 UTC, phorward commented
@sveneberth can you please make a review as well on this?

2024-01-19 14:47 UTC, sveneberth requested changes

2024-01-19 14:47 UTC, sveneberth commented on src/viur/core/skeleton.py
> +            if not db_key:
IMO it's easier to understand if you would switch the if/else blocks and remove the `not`.

2024-01-19 14:47 UTC, sveneberth commented on src/viur/core/skeleton.py
> +                for lang, value in list(current_seo_keys.items()):
I think the list case is not necessary here
```suggestion
                for lang, value in current_seo_keys.items():
```

2024-01-19 14:47 UTC, sveneberth commented on src/viur/core/skeleton.py
> +                    old_blob_lock_obj["old_blob_references"] = [removed_blob for removed_blob in removed_blobs]
```suggestion
                    old_blob_lock_obj["old_blob_references"] = list(removed_blobs)
```

2024-01-19 14:47 UTC, sveneberth commented on src/viur/core/skeleton.py
> +                    old_blob_refs += set([removed_blob for removed_blob in removed_blobs])  # Add removed blobs
```suggestion
                    old_blob_refs.update(removed_blobs)  # Add removed blobs
```

2024-01-19 14:47 UTC, sveneberth commented on src/viur/core/skeleton.py
> +                    old_blob_lock_obj["old_blob_references"] = [old_blob_ref for old_blob_ref in old_blob_refs]
```suggestion
                    old_blob_lock_obj["old_blob_references"] = list(old_blob_refs)
```

2024-01-22 11:22 UTC, phorward requested changes
@ArneGudermann can you resolve [the comment](https://github.com/viur-framework/viur-core/pull/973#discussion_r1459105588) from @sveneberth?

2024-01-22 11:52 UTC, phorward requested changes
Almost finished! :smile:

2024-01-22 11:52 UTC, phorward commented on src/viur/core/skeleton.py
> +            if is_add:
Please use modern syntax!
```suggestion
            if is_add := not bool(db_key):
```

2024-01-22 12:15 UTC, phorward submitted a review, later dismissed

2024-01-23 12:57 UTC, sveneberth commented
@ArneGudermann Can you resolve the merge conflict?

2024-01-24 15:27 UTC, sveneberth requested changes

2024-01-24 15:27 UTC, sveneberth commented on src/viur/core/skeleton.py
> +                    db_obj["viur"][f"{key}_uniqueIndexValue"] = new_unique_values
```
   db_obj["viur"][f"{db_key}_uniqueIndexValue"] = new_unique_values
NameError: free variable 'key' referenced before assignment in enclosing scope
```

```suggestion
                    db_obj["viur"][f"{db_key}_uniqueIndexValue"] = new_unique_values
```

2024-01-24 15:32 UTC, sveneberth commented on src/viur/core/skeleton.py
> +                    db_obj["viur"][f"{db_key}_uniqueIndexValue"] = new_unique_values
Ahh, @phorward you were to fast. `bone_name` would be correct. _db_key_ was simply too straightforward

```suggestion
                    db_obj["viur"][f"{bone_name}_uniqueIndexValue"] = new_unique_values
```

2024-01-24 15:40 UTC, sveneberth approved these changes

2024-01-24 15:43 UTC, phorward approved these changes

2024-01-24 15:44 UTC, merged