feat: `UserAuthentication`s with skeleton patch capability / customizable `PasswordBone`
viur-framework/viur-core pull request #983
Opened 2023-12-08 23:00 UTC by phorward

This pull request improves the standard `User` module to the following:

- `UserAuthentication` allows for a `@classmethod` to dynamically extend the UserSkel based on the authentication options which are configured. This e.g. only adds the fields for Google login to the UserSkel when `GoogleLogin` is configured, otherwise the fields are simply not there.
- `UserPassword` should be customizable with an individual `PasswordBone` that can be configured for the project, e.g. when it has another threshold. So it can be defined like this:
    ```python
    class UserPassword(UserPassword):
        # set customized PasswordBone
        PasswordBone = CustomPasswordBone
    ```

The pull request is still under development and not ready to merge.

2024-01-29 16:44 UTC, ArneGudermann approved these changes

2024-01-30 12:46 UTC, sveneberth requested changes
This leads, unfortunately, to most of the bones no longer being included in a RebuildSearchIndex. This can lead to problems with custom database adapters. And I don't know what happens with relations to the UserSkel.

2024-02-02 10:32 UTC, phorward commented
> This leads, unfortunately, to most of the bones no longer being included in a RebuildSearchIndex. This can lead to problems with custom database adapters. And I don't know what happens with relations to the UserSkel.

Hello @sveneberth, commit [9bcefb5](https://github.com/viur-framework/viur-core/pull/983/commits/9bcefb50b44808f7a50562675d3eeadd2b11868f) uses an improved approach to eliminate your concerns. Thanks for pointing these out.

2024-02-02 16:22 UTC, phorward commented on src/viur/core/modules/user.py
>      def getAuthMethodName(*args, **kwargs):
I've focused on this in a separate pull request #1059.

2024-02-02 16:33 UTC, sveneberth submitted a review, later dismissed

2024-02-02 17:33 UTC, merged