fix: Provide "moduleGroups" in `/vi/config`
viur-framework/viur-core pull request #994
Opened 2023-12-13 20:51 UTC by sveneberth

The vi-admin expects "moduleGroups" in `/vi/config`: https://github.com/viur-framework/vi-vue-components/blob/b7d21dacb93003bbf85f89ee51f3e0ec2f9433c6/components/screens/TheMainScreen.vue#L113

This patch add the related conf variable and ensures the value will be available under the old name (and the new, as in the conf itself: `admin.module_groups`).

Regression of #979

2023-12-14 06:29 UTC, XeoN-GHMB commented
The admin should support new "module_groups" and old "moduleGroups config. We shouldn't readd the old name

2023-12-14 10:28 UTC, phorward requested changes
Hello @sveneberth,
as @XeoN-GHMB commented, it will be fixed in viur-admin.

Nevertheless, please don't use the wording "Vi" anymore, as it is an excellent editor for Unix-like systems.

The "sortindex"-thing must be fixed both in the example and in viur-admin as well @XeoN-GHMB

2023-12-14 10:28 UTC, phorward commented on src/viur/core/config.py
> +    """primary color for the VI"""
```suggestion
    """primary color for viur-admin"""
```

2023-12-14 10:28 UTC, phorward commented on src/viur/core/config.py
> +    """secondary color for the VI"""
```suggestion
    """secondary color for viur-admin"""
```

2023-12-14 10:28 UTC, phorward commented on src/viur/core/config.py
> +    module_groups: dict[str, dict[Literal["name", "icon", "sortindex"], str | int]] = {}
`sortindex` defined, but `sortIndex` given below?

2023-12-14 10:28 UTC, phorward commented on src/viur/core/render/vi/__init__.py
> +
According to @XeoN-GHMB's comment, this viur-admin should fix this.
```suggestion
```

2023-12-15 13:28 UTC, sveneberth commented on src/viur/core/config.py
> +                "sortIndex": 20,
```suggestion
                "sortindex": 10,
            },
            "shop": {
                "name": "Shop",
                "icon": "cart",
                "sortindex": 20,
```

2023-12-15 13:30 UTC, sveneberth commented
@XeoN-GHMB Please use also the lowercase-only "sortindex" key name

2023-12-20 22:07 UTC, phorward approved these changes

2024-01-09 12:48 UTC, ArneGudermann approved these changes

2024-01-09 12:55 UTC, merged